// =============================================================================
// GENERATED CARD CONFIG CONTRACT - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================
var CARD_CONFIG_FIELDS = ["entity", "label", "icon", "icon_on", "sensor", "unit", "type", "precision", "options"];
var CARD_CONTRACT_CARDS = {
  "": {
    "label": "Switch",
    "allowInSubpage": true,
    "domains": [
      "light",
      "switch",
      "input_boolean",
      "fan"
    ],
    "options": [
      {
        "name": "confirmation_mode",
        "label": "Confirmation Required",
        "kind": "choice",
        "values": [
          "",
          "off",
          "on",
          "both"
        ],
        "defaultValue": "",
        "storage": [
          "confirm_off",
          "confirm_on"
        ]
      },
      {
        "name": "confirm_message",
        "label": "Message",
        "kind": "text",
        "defaultValue": "Turn off this device?",
        "defaultValueByMode": {
          "off": "Turn off this device?",
          "on": "Turn on this device?",
          "both": "Toggle this device?"
        }
      },
      {
        "name": "confirm_yes",
        "label": "Confirm Button",
        "kind": "text",
        "defaultValue": "Yes"
      },
      {
        "name": "confirm_no",
        "label": "Cancel Button",
        "kind": "text",
        "defaultValue": "No"
      }
    ],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Auto",
      "icon_on": "Auto",
      "sensor": "",
      "unit": "",
      "type": "",
      "precision": "",
      "options": ""
    }
  },
  "action": {
    "label": "Action",
    "allowInSubpage": true,
    "domains": [
      "scene",
      "script",
      "automation",
      "button",
      "vacuum",
      "input_button",
      "input_boolean",
      "input_number",
      "input_select",
      "select"
    ],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Flash",
      "icon_on": "Auto",
      "sensor": "scene.turn_on",
      "unit": "",
      "type": "action",
      "precision": "",
      "options": ""
    }
  },
  "alarm": {
    "label": "Alarm",
    "allowInSubpage": true,
    "domains": [
      "alarm_control_panel"
    ],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Security",
      "icon_on": "Auto",
      "sensor": "",
      "unit": "",
      "type": "alarm",
      "precision": "",
      "options": ""
    }
  },
  "alarm_action": {
    "label": "Alarm",
    "allowInSubpage": true,
    "pickerKey": "alarm",
    "domains": [
      "alarm_control_panel"
    ],
    "default": {
      "entity": "",
      "label": "Arm Away",
      "icon": "Shield Lock",
      "icon_on": "Auto",
      "sensor": "away",
      "unit": "",
      "type": "alarm_action",
      "precision": "",
      "options": ""
    }
  },
  "calendar": {
    "label": "Date & Time",
    "allowInSubpage": true,
    "domains": [
      "sensor"
    ],
    "options": [
      {
        "name": "date_time_mode",
        "label": "Type",
        "kind": "choice",
        "values": [
          "datetime",
          "",
          "timezone"
        ],
        "defaultValue": ""
      },
      {
        "name": "large_numbers",
        "label": "Large Date / Time Numbers",
        "kind": "flag"
      }
    ],
    "default": {
      "entity": "sensor.date",
      "label": "",
      "icon": "Auto",
      "icon_on": "Auto",
      "sensor": "",
      "unit": "",
      "type": "calendar",
      "precision": "",
      "options": ""
    }
  },
  "climate": {
    "label": "Climate",
    "allowInSubpage": true,
    "domains": [
      "climate"
    ],
    "default": {
      "entity": "",
      "label": "Climate",
      "icon": "Thermostat",
      "icon_on": "Auto",
      "sensor": "",
      "unit": "",
      "type": "climate",
      "precision": "",
      "options": ""
    }
  },
  "cover": {
    "label": "Cover",
    "allowInSubpage": true,
    "domains": [
      "cover"
    ],
    "options": [
      {
        "name": "cover_mode",
        "label": "Type",
        "kind": "choice",
        "values": [
          "",
          "tilt",
          "toggle",
          "open",
          "close",
          "stop",
          "set_position"
        ],
        "defaultValue": ""
      },
      {
        "name": "cover_position",
        "label": "Position",
        "kind": "number",
        "defaultValue": "50",
        "min": 0,
        "max": 100,
        "step": 1
      }
    ],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Blinds",
      "icon_on": "Blinds Open",
      "sensor": "",
      "unit": "",
      "type": "cover",
      "precision": "",
      "options": ""
    }
  },
  "door_window": {
    "label": "Doors & Windows",
    "allowInSubpage": true,
    "domains": [
      "binary_sensor",
      "sensor"
    ],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Door",
      "icon_on": "Door Open",
      "sensor": "",
      "unit": "",
      "type": "door_window",
      "precision": "door",
      "options": "active_color"
    }
  },
  "fan_direction": {
    "label": "Fans",
    "allowInSubpage": true,
    "pickerKey": "fan_speed",
    "experimental": "developer",
    "domains": [
      "fan"
    ],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Swap Horizontal",
      "icon_on": "Auto",
      "sensor": "",
      "unit": "",
      "type": "fan_direction",
      "precision": "",
      "options": ""
    }
  },
  "fan_oscillate": {
    "label": "Fans",
    "allowInSubpage": true,
    "pickerKey": "fan_speed",
    "experimental": "developer",
    "domains": [
      "fan"
    ],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Fan",
      "icon_on": "Auto",
      "sensor": "",
      "unit": "",
      "type": "fan_oscillate",
      "precision": "",
      "options": ""
    }
  },
  "fan_preset": {
    "label": "Fans",
    "allowInSubpage": true,
    "pickerKey": "fan_speed",
    "experimental": "developer",
    "domains": [
      "fan"
    ],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Fan Auto",
      "icon_on": "Auto",
      "sensor": "",
      "unit": "",
      "type": "fan_preset",
      "precision": "",
      "options": ""
    }
  },
  "fan_speed": {
    "label": "Fans",
    "allowInSubpage": true,
    "experimental": "developer",
    "domains": [
      "fan"
    ],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Fan Speed 2",
      "icon_on": "Auto",
      "sensor": "",
      "unit": "",
      "type": "fan_speed",
      "precision": "",
      "options": ""
    }
  },
  "fan_switch": {
    "label": "Fans",
    "allowInSubpage": true,
    "pickerKey": "fan_speed",
    "experimental": "developer",
    "domains": [
      "fan"
    ],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Fan Off",
      "icon_on": "Fan",
      "sensor": "",
      "unit": "",
      "type": "fan_switch",
      "precision": "",
      "options": ""
    }
  },
  "garage": {
    "label": "Garage Door",
    "allowInSubpage": true,
    "domains": [
      "cover"
    ],
    "options": [
      {
        "name": "garage_mode",
        "label": "Interaction",
        "kind": "choice",
        "values": [
          "",
          "open",
          "close"
        ],
        "defaultValue": ""
      },
      {
        "name": "label_display",
        "label": "Display",
        "kind": "choice",
        "values": [
          "label",
          "status"
        ],
        "defaultValue": "label"
      }
    ],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Garage",
      "icon_on": "Garage Open",
      "sensor": "",
      "unit": "",
      "type": "garage",
      "precision": "",
      "options": ""
    }
  },
  "internal": {
    "label": "Internal Switches",
    "allowInSubpage": true,
    "domains": [],
    "options": [
      {
        "name": "internal_mode",
        "label": "Mode",
        "kind": "choice",
        "values": [
          "switch",
          "push"
        ],
        "defaultValue": "switch"
      }
    ],
    "behavior": {
      "internalRelay": {
        "defaultIcons": {
          "switch": "Lightbulb Outline",
          "push": "Gesture Tap"
        },
        "defaultIconOn": "Lightbulb"
      }
    },
    "default": {
      "entity": "",
      "label": "",
      "icon": "Power",
      "icon_on": "Flash",
      "sensor": "",
      "unit": "",
      "type": "internal",
      "precision": "",
      "options": ""
    }
  },
  "light_brightness": {
    "label": "Lights",
    "allowInSubpage": true,
    "domains": [
      "light"
    ],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Lightbulb Outline",
      "icon_on": "Lightbulb",
      "sensor": "",
      "unit": "",
      "type": "light_brightness",
      "precision": "",
      "options": ""
    }
  },
  "light_switch": {
    "label": "Lights",
    "allowInSubpage": true,
    "pickerKey": "light_brightness",
    "domains": [
      "light"
    ],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Lightbulb Outline",
      "icon_on": "Lightbulb",
      "sensor": "",
      "unit": "",
      "type": "light_switch",
      "precision": "",
      "options": ""
    }
  },
  "light_temperature": {
    "label": "Lights",
    "allowInSubpage": true,
    "pickerKey": "light_brightness",
    "domains": [
      "light"
    ],
    "behavior": {
      "lightTemperature": {
        "defaultRange": "2000-6500",
        "min": 1000,
        "max": 10000,
        "minMax": 9900,
        "step": 100,
        "legacySensorValues": [
          "kelvin"
        ]
      }
    },
    "default": {
      "entity": "",
      "label": "",
      "icon": "Lightbulb",
      "icon_on": "Auto",
      "sensor": "",
      "unit": "2000-6500",
      "type": "light_temperature",
      "precision": "",
      "options": ""
    }
  },
  "lock": {
    "label": "Lock",
    "allowInSubpage": true,
    "domains": [
      "lock"
    ],
    "options": [
      {
        "name": "lock_mode",
        "label": "Type",
        "kind": "choice",
        "values": [
          "",
          "lock",
          "unlock"
        ],
        "defaultValue": ""
      }
    ],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Lock",
      "icon_on": "Lock Open",
      "sensor": "",
      "unit": "",
      "type": "lock",
      "precision": "",
      "options": ""
    }
  },
  "media": {
    "label": "Media",
    "allowInSubpage": true,
    "domains": [
      "media_player"
    ],
    "options": [
      {
        "name": "media_mode",
        "label": "Type",
        "kind": "choice",
        "values": [
          "play_pause",
          "previous",
          "next",
          "volume",
          "position",
          "now_playing"
        ],
        "defaultValue": "play_pause"
      },
      {
        "name": "media_display",
        "label": "Type",
        "kind": "choice",
        "values": [
          "",
          "state"
        ],
        "defaultValue": ""
      },
      {
        "name": "media_now_playing_controls",
        "label": "Controls",
        "kind": "choice",
        "values": [
          "",
          "progress",
          "play_pause"
        ],
        "defaultValue": ""
      }
    ],
    "behavior": {
      "media": {
        "defaultMode": "play_pause",
        "legacyModes": {
          "controls": "play_pause"
        },
        "stateDisplayModes": [
          "play_pause",
          "position"
        ]
      }
    },
    "default": {
      "entity": "",
      "label": "",
      "icon": "Auto",
      "icon_on": "Auto",
      "sensor": "play_pause",
      "unit": "",
      "type": "media",
      "precision": "",
      "options": ""
    }
  },
  "option_select": {
    "label": "Option Select",
    "allowInSubpage": true,
    "hidden": true,
    "domains": [
      "select",
      "input_select"
    ],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Flash",
      "icon_on": "Auto",
      "sensor": "input_select.select_option",
      "unit": "",
      "type": "action",
      "precision": "",
      "options": ""
    }
  },
  "push": {
    "label": "Trigger",
    "allowInSubpage": true,
    "domains": [],
    "behavior": {
      "pushAction": {
        "defaultIcon": "Gesture Tap",
        "defaultIconOn": "Auto"
      }
    },
    "default": {
      "entity": "",
      "label": "",
      "icon": "Gesture Tap",
      "icon_on": "Auto",
      "sensor": "",
      "unit": "",
      "type": "push",
      "precision": "",
      "options": ""
    }
  },
  "sensor": {
    "label": "Sensor",
    "allowInSubpage": true,
    "domains": [
      "sensor",
      "binary_sensor",
      "text_sensor"
    ],
    "options": [
      {
        "name": "large_numbers",
        "label": "Large Sensor Numbers",
        "kind": "flag",
        "supportedWhen": {
          "precisionNot": [
            "text"
          ]
        }
      },
      {
        "name": "active_color",
        "label": "Active Color",
        "kind": "flag",
        "hidden": true,
        "migration": "drop",
        "supportedWhen": {
          "never": true
        }
      }
    ],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Auto",
      "icon_on": "Auto",
      "sensor": "",
      "unit": "",
      "type": "sensor",
      "precision": "",
      "options": ""
    }
  },
  "slider": {
    "label": "Slider",
    "allowInSubpage": true,
    "domains": [
      "light",
      "fan"
    ],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Auto",
      "icon_on": "Auto",
      "sensor": "",
      "unit": "",
      "type": "slider",
      "precision": "",
      "options": ""
    }
  },
  "subpage": {
    "label": "Subpage",
    "allowInSubpage": false,
    "domains": [],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Auto",
      "icon_on": "Auto",
      "sensor": "",
      "unit": "",
      "type": "subpage",
      "precision": "",
      "options": ""
    }
  },
  "timezone": {
    "label": "Date & Time",
    "allowInSubpage": true,
    "domains": [],
    "options": [
      {
        "name": "date_time_mode",
        "label": "Type",
        "kind": "choice",
        "values": [
          "datetime",
          "",
          "timezone"
        ],
        "defaultValue": "timezone"
      },
      {
        "name": "large_numbers",
        "label": "Large Date / Time Numbers",
        "kind": "flag"
      }
    ],
    "default": {
      "entity": "UTC (GMT+0)",
      "label": "",
      "icon": "Auto",
      "icon_on": "Auto",
      "sensor": "",
      "unit": "",
      "type": "timezone",
      "precision": "",
      "options": ""
    }
  },
  "weather": {
    "label": "Weather",
    "allowInSubpage": true,
    "domains": [
      "weather"
    ],
    "options": [
      {
        "name": "weather_mode",
        "label": "Type",
        "kind": "choice",
        "values": [
          "",
          "today",
          "tomorrow"
        ],
        "defaultValue": ""
      },
      {
        "name": "large_numbers",
        "label": "Large Temperature Numbers",
        "kind": "flag",
        "supportedWhen": {
          "precision": [
            "today",
            "tomorrow"
          ]
        }
      }
    ],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Auto",
      "icon_on": "Auto",
      "sensor": "",
      "unit": "",
      "type": "weather",
      "precision": "",
      "options": ""
    }
  },
  "weather_forecast": {
    "label": "Weather Forecast",
    "allowInSubpage": true,
    "hidden": true,
    "domains": [
      "weather"
    ],
    "default": {
      "entity": "",
      "label": "",
      "icon": "Auto",
      "icon_on": "Auto",
      "sensor": "",
      "unit": "",
      "type": "weather",
      "precision": "tomorrow",
      "options": ""
    }
  }
};
var CARD_CONTRACT_MIGRATION_ALIASES = {
  "option_select": {
    "type": "action",
    "sensor": "input_select.select_option"
  },
  "text_sensor": {
    "type": "sensor",
    "precision": "text"
  },
  "weather_forecast": {
    "type": "weather",
    "precision": "tomorrow"
  }
};
var CARD_CONTRACT_BRIGHTNESS_SLIDER_TYPES = ["slider", "light_brightness", "fan_speed"];
var CARD_CONTRACT_FAN_DEFAULT_ICONS = {
  "fan_switch": "Fan Off",
  "fan_speed": "Fan Speed 2",
  "fan_oscillate": "Fan",
  "fan_direction": "Swap Horizontal",
  "fan_preset": "Fan Auto"
};
var CARD_CONTRACT_FAN_DEFAULT_ICON_ON = {
  "fan_switch": "Fan"
};
var CARD_CONTRACT_OPTION_SELECT_ACTION = "input_select.select_option";
var CARD_CONTRACT_OPTION_SELECT_ACTIONS = ["input_select.select_option", "select.select_option"];
var CARD_CONTRACT_SUBPAGE_TYPE_CODES = {
  "action": "A",
  "calendar": "D",
  "timezone": "T",
  "sensor": "S",
  "door_window": "X",
  "weather": "W",
  "weather_forecast": "F",
  "option_select": "U",
  "fan_switch": "B",
  "fan_speed": "J",
  "fan_oscillate": "O",
  "fan_direction": "E",
  "fan_preset": "Z",
  "light_brightness": "V",
  "light_switch": "Q",
  "alarm": "Y",
  "alarm_action": "AA",
  "slider": "L",
  "cover": "C",
  "light_temperature": "N",
  "garage": "R",
  "lock": "K",
  "media": "M",
  "climate": "H",
  "push": "P",
  "internal": "I",
  "subpage": "G"
};
var CARD_CONTRACT_SUBPAGE_TYPES_BY_CODE = {
  "A": "action",
  "D": "calendar",
  "T": "timezone",
  "S": "sensor",
  "X": "door_window",
  "W": "weather",
  "F": "weather_forecast",
  "U": "option_select",
  "B": "fan_switch",
  "J": "fan_speed",
  "O": "fan_oscillate",
  "E": "fan_direction",
  "Z": "fan_preset",
  "V": "light_brightness",
  "Q": "light_switch",
  "Y": "alarm",
  "AA": "alarm_action",
  "L": "slider",
  "C": "cover",
  "N": "light_temperature",
  "R": "garage",
  "K": "lock",
  "M": "media",
  "H": "climate",
  "P": "push",
  "I": "internal",
  "G": "subpage"
};
var CARD_CONTRACT_LARGE_NUMBERS = {
  "sensor": {
    "excludedPrecisions": [
      "text"
    ]
  },
  "weather": {
    "precisions": [
      "today",
      "tomorrow"
    ]
  },
  "calendar": true,
  "timezone": true
};

function cardContractListContains(list, value) {
  return (list || []).indexOf(value) >= 0;
}

function cardContractCard(type) {
  return CARD_CONTRACT_CARDS[type || ""] || null;
}

function cardContractCardKeys() {
  return Object.keys(CARD_CONTRACT_CARDS);
}

function cardContractCardLabel(type) {
  var card = cardContractCard(type);
  return card ? card.label : (type || "Switch");
}

function cardContractAllowInSubpage(type) {
  var card = cardContractCard(type);
  return !!(card && card.allowInSubpage);
}

function cardContractPickerKey(type) {
  var card = cardContractCard(type);
  return card && card.pickerKey ? card.pickerKey : "";
}

function cardContractExperimental(type) {
  var card = cardContractCard(type);
  return card && card.experimental ? card.experimental : "";
}

function cardContractHidden(type) {
  var card = cardContractCard(type);
  return !!(card && card.hidden);
}

function cardContractOptions(type) {
  var card = cardContractCard(type);
  return card && card.options ? JSON.parse(JSON.stringify(card.options)) : [];
}

function cardContractDefaultConfig(type) {
  var card = cardContractCard(type);
  var defaults = card && card.default ? card.default : CARD_CONTRACT_CARDS[""].default;
  return Object.assign({}, defaults);
}

function cardContractDomains(type) {
  var card = cardContractCard(type);
  return card && card.domains ? card.domains.slice() : [];
}

function cardContractMigrationAlias(type) {
  var alias = CARD_CONTRACT_MIGRATION_ALIASES[type || ""];
  return alias ? Object.assign({}, alias) : null;
}

function cardContractIsBrightnessSliderType(type) {
  return cardContractListContains(CARD_CONTRACT_BRIGHTNESS_SLIDER_TYPES, type);
}

function cardContractIsFanCardType(type) {
  return Object.prototype.hasOwnProperty.call(CARD_CONTRACT_FAN_DEFAULT_ICONS, type || "");
}

function cardContractFanDefaultIcon(type) {
  return CARD_CONTRACT_FAN_DEFAULT_ICONS[type] || CARD_CONTRACT_FAN_DEFAULT_ICONS.fan_speed || "Fan Speed 2";
}

function cardContractFanDefaultIconOn(type) {
  return CARD_CONTRACT_FAN_DEFAULT_ICON_ON[type] || "Auto";
}

function cardContractIsOptionSelectType(type) {
  return type === "option_select";
}

function cardContractIsOptionSelectAction(action) {
  return cardContractListContains(CARD_CONTRACT_OPTION_SELECT_ACTIONS, action);
}

function cardContractSubpageTypeCode(type) {
  return CARD_CONTRACT_SUBPAGE_TYPE_CODES[type || ""] || (type || "");
}

function cardContractSubpageTypeFromCode(code) {
  return CARD_CONTRACT_SUBPAGE_TYPES_BY_CODE[code || ""] || (code || "");
}

function cardContractLargeNumbersSupported(type, precision) {
  var rule = CARD_CONTRACT_LARGE_NUMBERS[type || ""];
  if (rule === true) return true;
  if (!rule) return false;
  if (rule.excludedPrecisions) return !cardContractListContains(rule.excludedPrecisions, precision || "");
  if (rule.precisions) return cardContractListContains(rule.precisions, precision || "");
  return false;
}
