// =============================================================================
// GENERATED ENTITY CATALOG - do not edit by hand
// Generated by scripts/build.py from common/config/entity_names.json.
// =============================================================================
var ENTITY_CATALOG = {
  "entities": {
    "button_order": {
      "domain": "text",
      "name": "Button Order"
    },
    "screen_theme": {
      "domain": "select",
      "name": "Screen: Theme",
      "objectIds": [
        "screen__theme",
        "screen_theme"
      ]
    },
    "button_on_color": {
      "domain": "text",
      "name": "Button On Color"
    },
    "button_off_color": {
      "domain": "text",
      "name": "Button Off Color"
    },
    "sensor_card_color": {
      "domain": "text",
      "name": "Sensor Card Color"
    },
    "button_config": {
      "domain": "text",
      "template": "Button {slot} Config"
    },
    "subpage_config": {
      "domain": "text",
      "template": "Subpage {slot} Config"
    },
    "subpage_config_ext": {
      "domain": "text",
      "template": "Subpage {slot} Config Ext"
    },
    "subpage_config_ext_2": {
      "domain": "text",
      "template": "Subpage {slot} Config Ext 2"
    },
    "subpage_config_ext_3": {
      "domain": "text",
      "template": "Subpage {slot} Config Ext 3"
    },
    "subpage_config_ext_4": {
      "domain": "text",
      "template": "Subpage {slot} Config Ext 4"
    },
    "subpage_config_ext_5": {
      "domain": "text",
      "template": "Subpage {slot} Config Ext 5"
    },
    "subpage_config_ext_6": {
      "domain": "text",
      "template": "Subpage {slot} Config Ext 6"
    },
    "subpage_config_ext_7": {
      "domain": "text",
      "template": "Subpage {slot} Config Ext 7"
    },
    "indoor_temp_enable": {
      "domain": "switch",
      "name": "Indoor Temp Enable"
    },
    "outdoor_temp_enable": {
      "domain": "switch",
      "name": "Outdoor Temp Enable"
    },
    "screen_clock_bar": {
      "domain": "switch",
      "name": "Screen: Clock Bar",
      "objectIds": [
        "screen__clock_bar",
        "screen_clock_bar",
        "clock_bar_enabled"
      ]
    },
    "screen_network_status_icon": {
      "domain": "switch",
      "name": "Screen: Network Status Icon",
      "objectIds": [
        "screen__network_status_icon",
        "screen_network_status_icon",
        "network_status_enabled"
      ]
    },
    "screen_temperature_degree_symbol": {
      "domain": "switch",
      "name": "Screen: Temperature Degree Symbol",
      "objectIds": [
        "screen__temperature_degree_symbol",
        "screen_temperature_degree_symbol",
        "temperature_degree_symbol_enabled"
      ]
    },
    "screen_subpage_chevron": {
      "domain": "switch",
      "name": "Screen: Subpage Chevron",
      "objectIds": [
        "screen__subpage_chevron",
        "screen_subpage_chevron",
        "subpage_chevrons_enabled"
      ]
    },
    "screen_temperature_unit": {
      "domain": "select",
      "name": "Screen: Temperature Unit"
    },
    "indoor_temp_entity": {
      "domain": "text",
      "name": "Indoor Temp Entity"
    },
    "outdoor_temp_entity": {
      "domain": "text",
      "name": "Outdoor Temp Entity"
    },
    "screensaver_mode": {
      "domain": "text",
      "name": "Screensaver Mode"
    },
    "screen_saver_action": {
      "domain": "select",
      "name": "Screen Saver: Action",
      "objectIds": [
        "screen_saver__action",
        "screen_saver_action",
        "screensaver_action"
      ]
    },
    "presence_sensor_entity": {
      "domain": "text",
      "name": "Presence Sensor Entity"
    },
    "screen_saver_media_player_sleep_prevention": {
      "domain": "switch",
      "name": "Screen Saver: Media Player Sleep Prevention"
    },
    "media_player_sleep_prevention_entity": {
      "domain": "text",
      "name": "Media Player Sleep Prevention Entity"
    },
    "screen_saver_daytime_clock_brightness": {
      "domain": "number",
      "name": "Screen Saver: Daytime Clock Brightness",
      "objectIds": [
        "screen_saver__daytime_clock_brightness",
        "screen_saver__clock_brightness"
      ]
    },
    "screen_saver_nighttime_clock_brightness": {
      "domain": "number",
      "name": "Screen Saver: Nighttime Clock Brightness",
      "objectIds": [
        "screen_saver__nighttime_clock_brightness",
        "screen_saver__clock_brightness"
      ]
    },
    "screen_saver_clock_brightness": {
      "domain": "number",
      "name": "Screen Saver: Clock Brightness"
    },
    "screen_saver_dimmed_brightness": {
      "domain": "number",
      "name": "Screen Saver: Dimmed Brightness",
      "objectIds": [
        "screen_saver__dimmed_brightness",
        "screen_saver_dimmed_brightness",
        "screensaver_dimmed_brightness"
      ]
    },
    "screensaver_timeout": {
      "domain": "number",
      "name": "Screensaver Timeout",
      "objectIds": [
        "screensaver_timeout"
      ]
    },
    "home_screen_timeout": {
      "domain": "number",
      "name": "Home Screen Timeout"
    },
    "screen_saver_clock": {
      "domain": "switch",
      "name": "Screen Saver: Clock"
    },
    "screen_timezone": {
      "domain": "select",
      "name": "Screen: Timezone"
    },
    "screen_clock_format": {
      "domain": "select",
      "name": "Screen: Clock Format"
    },
    "screen_ntp_server_1": {
      "domain": "text",
      "name": "Screen: NTP Server 1"
    },
    "screen_ntp_server_2": {
      "domain": "text",
      "name": "Screen: NTP Server 2"
    },
    "screen_ntp_server_3": {
      "domain": "text",
      "name": "Screen: NTP Server 3"
    },
    "screen_month_names": {
      "domain": "text",
      "name": "Screen: Month Names"
    },
    "screen_sunrise": {
      "domain": "text_sensor",
      "name": "Screen: Sunrise"
    },
    "screen_sunset": {
      "domain": "text_sensor",
      "name": "Screen: Sunset"
    },
    "network_transport": {
      "domain": "text_sensor",
      "name": "Network Transport"
    },
    "wifi_strength": {
      "domain": "sensor",
      "name": "Wifi Strength"
    },
    "screen_automatic_brightness": {
      "domain": "switch",
      "name": "Screen: Automatic Brightness",
      "objectIds": [
        "screen__automatic_brightness"
      ]
    },
    "screen_schedule_enabled": {
      "domain": "switch",
      "name": "Screen: Schedule Enabled",
      "objectIds": [
        "screen__schedule_enabled"
      ]
    },
    "screen_schedule_mode": {
      "domain": "select",
      "name": "Screen: Schedule Mode",
      "objectIds": [
        "screen__schedule_mode"
      ]
    },
    "screen_schedule_on_hour": {
      "domain": "number",
      "name": "Screen: Schedule On Hour",
      "objectIds": [
        "screen__schedule_on_hour"
      ]
    },
    "screen_schedule_off_hour": {
      "domain": "number",
      "name": "Screen: Schedule Off Hour",
      "objectIds": [
        "screen__schedule_off_hour"
      ]
    },
    "screen_schedule_wake_timeout": {
      "domain": "number",
      "name": "Screen: Schedule Wake Timeout",
      "objectIds": [
        "screen__schedule_wake_timeout",
        "screen_schedule_wake_timeout",
        "schedule_wake_timeout"
      ]
    },
    "screen_schedule_wake_brightness": {
      "domain": "number",
      "name": "Screen: Schedule Wake Brightness",
      "objectIds": [
        "screen__schedule_wake_brightness",
        "screen_schedule_wake_brightness",
        "schedule_wake_brightness"
      ]
    },
    "screen_schedule_dimmed_brightness": {
      "domain": "number",
      "name": "Screen: Schedule Dimmed Brightness",
      "objectIds": [
        "screen__schedule_dimmed_brightness",
        "screen_schedule_dimmed_brightness",
        "schedule_dimmed_brightness"
      ]
    },
    "screen_schedule_clock_brightness": {
      "domain": "number",
      "name": "Screen: Schedule Clock Brightness",
      "objectIds": [
        "screen__schedule_clock_brightness",
        "screen_schedule_clock_brightness",
        "schedule_clock_brightness"
      ]
    },
    "screen_schedule_clock_text_color": {
      "domain": "text",
      "name": "Screen: Schedule Clock Text Color",
      "objectIds": [
        "screen__schedule_clock_text_color",
        "screen_schedule_clock_text_color",
        "schedule_clock_text_color"
      ]
    },
    "screen_daytime_brightness": {
      "domain": "number",
      "name": "Screen: Daytime Brightness"
    },
    "screen_nighttime_brightness": {
      "domain": "number",
      "name": "Screen: Nighttime Brightness"
    },
    "firmware_version": {
      "domain": "text_sensor",
      "name": "Firmware: Version",
      "objectIds": [
        "firmware__version",
        "firmware_version",
        "firmware_version_sensor"
      ]
    },
    "firmware_update": {
      "domain": "update",
      "name": "Firmware: Update",
      "objectIds": [
        "firmware__update",
        "firmware_update"
      ]
    },
    "firmware_check_for_update": {
      "domain": "button",
      "name": "Firmware: Check for Update",
      "objectIds": [
        "firmware__check_for_update",
        "firmware_check_for_update"
      ]
    },
    "firmware_install_update": {
      "domain": "button",
      "name": "Firmware: Install Update",
      "objectIds": [
        "firmware__install_update",
        "firmware_install_update"
      ]
    },
    "firmware_auto_update": {
      "domain": "switch",
      "name": "Firmware: Auto Update"
    },
    "firmware_update_frequency": {
      "domain": "select",
      "name": "Firmware: Update Frequency"
    },
    "developer_experimental_features": {
      "domain": "switch",
      "name": "Developer: Experimental Features",
      "objectIds": [
        "developer__experimental_features",
        "developer_experimental_features"
      ]
    },
    "screen_rotation": {
      "domain": "select",
      "name": "Screen: Rotation"
    }
  },
  "groups": {
    "card": [
      "button_order",
      "screen_theme",
      "button_on_color",
      "button_off_color",
      "sensor_card_color"
    ],
    "card_slot": [
      "button_config"
    ],
    "subpage_slot": [
      "subpage_config",
      "subpage_config_ext",
      "subpage_config_ext_2",
      "subpage_config_ext_3",
      "subpage_config_ext_4",
      "subpage_config_ext_5",
      "subpage_config_ext_6",
      "subpage_config_ext_7"
    ],
    "settings": [
      "indoor_temp_enable",
      "outdoor_temp_enable",
      "screen_clock_bar",
      "screen_network_status_icon",
      "screen_temperature_degree_symbol",
      "screen_subpage_chevron",
      "screen_temperature_unit",
      "indoor_temp_entity",
      "outdoor_temp_entity",
      "screensaver_mode",
      "screen_saver_action",
      "presence_sensor_entity",
      "screen_saver_media_player_sleep_prevention",
      "media_player_sleep_prevention_entity",
      "screen_saver_daytime_clock_brightness",
      "screen_saver_nighttime_clock_brightness",
      "screen_saver_clock_brightness",
      "screen_saver_dimmed_brightness",
      "screensaver_timeout",
      "home_screen_timeout",
      "screen_saver_clock",
      "screen_timezone",
      "screen_clock_format",
      "screen_ntp_server_1",
      "screen_ntp_server_2",
      "screen_ntp_server_3",
      "screen_month_names",
      "screen_sunrise",
      "screen_sunset",
      "network_transport",
      "wifi_strength",
      "screen_automatic_brightness",
      "screen_schedule_enabled",
      "screen_schedule_mode",
      "screen_schedule_on_hour",
      "screen_schedule_off_hour",
      "screen_schedule_wake_timeout",
      "screen_schedule_wake_brightness",
      "screen_schedule_dimmed_brightness",
      "screen_schedule_clock_brightness",
      "screen_schedule_clock_text_color",
      "screen_daytime_brightness",
      "screen_nighttime_brightness",
      "firmware_version",
      "firmware_update",
      "firmware_check_for_update",
      "firmware_install_update",
      "firmware_auto_update",
      "firmware_update_frequency",
      "developer_experimental_features"
    ],
    "settings_optional": [
      "screen_rotation"
    ]
  }
};
