// =============================================================================
// GENERATED WEB MODEL - do not edit by hand
// Generated by scripts/build.py from src/webserver/model/index.ts.
// =============================================================================
"use strict";
var EspControlModel = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // src/webserver/model/index.ts
  var index_exports = {};
  __export(index_exports, {
    BACKUP_CONFIG_VERSION: () => BACKUP_CONFIG_VERSION,
    BACKUP_FORMAT: () => BACKUP_FORMAT,
    CARD_CONFIG_FIELDS: () => CARD_CONFIG_FIELDS,
    CARD_SIZE_DEFINITIONS: () => CARD_SIZE_DEFINITIONS,
    CARD_SIZE_EXTRA_TALL: () => CARD_SIZE_EXTRA_TALL,
    CARD_SIZE_EXTRA_WIDE: () => CARD_SIZE_EXTRA_WIDE,
    CARD_SIZE_LARGE: () => CARD_SIZE_LARGE,
    CARD_SIZE_SINGLE: () => CARD_SIZE_SINGLE,
    CARD_SIZE_TALL: () => CARD_SIZE_TALL,
    CARD_SIZE_WIDE: () => CARD_SIZE_WIDE,
    applySpans: () => applySpans,
    backLabelFromOrder: () => backLabelFromOrder,
    backOrderToken: () => backOrderToken,
    backupOrderUsedSlots: () => backupOrderUsedSlots,
    backupPlaceSlotAt: () => backupPlaceSlotAt,
    backupSource: () => backupSource,
    buildSubpageGrid: () => buildSubpageGrid,
    cardConfigChanged: () => cardConfigChanged,
    cardSizeClass: () => cardSizeClass,
    cardSizeDefinition: () => cardSizeDefinition,
    chooseSerializedSubpageConfig: () => chooseSerializedSubpageConfig,
    clearSpans: () => clearSpans,
    cloneCardConfig: () => cloneCardConfig,
    copyCardConfig: () => copyCardConfig,
    coveredCells: () => coveredCells,
    createBackupEnvelope: () => createBackupEnvelope,
    decodeConfigField: () => decodeConfigField,
    emptyCardConfig: () => emptyCardConfig,
    encodeConfigField: () => encodeConfigField,
    isBackOrderToken: () => isBackOrderToken,
    legacyButtonConfigSafe: () => legacyButtonConfigSafe,
    legacySubpageFieldsSafe: () => legacySubpageFieldsSafe,
    markSpannedCells: () => markSpannedCells,
    normalizeBackupEnvelope: () => normalizeBackupEnvelope,
    normalizeBackupPanelSettings: () => normalizeBackupPanelSettings,
    normalizeBackupScreenSettings: () => normalizeBackupScreenSettings,
    normalizeClockBrightness: () => normalizeClockBrightness,
    normalizeHexColor: () => normalizeHexColor,
    normalizeHour: () => normalizeHour,
    normalizeLanguage: () => normalizeLanguage,
    normalizeNtpServer: () => normalizeNtpServer,
    normalizeScheduleClockBrightness: () => normalizeScheduleClockBrightness,
    normalizeScheduleDimmedBrightness: () => normalizeScheduleDimmedBrightness,
    normalizeScheduleMode: () => normalizeScheduleMode,
    normalizeScheduleTrigger: () => normalizeScheduleTrigger,
    normalizeScheduleWakeBrightness: () => normalizeScheduleWakeBrightness,
    normalizeScheduleWakeTimeout: () => normalizeScheduleWakeTimeout,
    normalizeScreensaverAction: () => normalizeScreensaverAction,
    normalizeScreensaverDimmedBrightness: () => normalizeScreensaverDimmedBrightness,
    normalizeTemperatureUnit: () => normalizeTemperatureUnit,
    normalizeTimeOfDay: () => normalizeTimeOfDay,
    parseBackOrderToken: () => parseBackOrderToken,
    parseCompactSubpageConfig: () => parseCompactSubpageConfig,
    parseGridOrder: () => parseGridOrder,
    parseLegacySubpageConfig: () => parseLegacySubpageConfig,
    parseRawButtonConfig: () => parseRawButtonConfig,
    parseRawSubpageConfig: () => parseRawSubpageConfig,
    parseStructuredSubpageConfig: () => parseStructuredSubpageConfig,
    parseSubpageOrder: () => parseSubpageOrder,
    planBackupButtonLayout: () => planBackupButtonLayout,
    scheduleModeOption: () => scheduleModeOption,
    screensaverActionOption: () => screensaverActionOption,
    serializeCompactSubpageConfig: () => serializeCompactSubpageConfig,
    serializeGridOrder: () => serializeGridOrder,
    serializeLegacySubpageConfig: () => serializeLegacySubpageConfig,
    serializeSubpageGrid: () => serializeSubpageGrid,
    sizeColSpan: () => sizeColSpan,
    sizeFitsAt: () => sizeFitsAt,
    sizeFromToken: () => sizeFromToken,
    sizeRowSpan: () => sizeRowSpan,
    sizeToken: () => sizeToken,
    splitSubpageConfigChunks: () => splitSubpageConfigChunks,
    structuredSubpageFromParsed: () => structuredSubpageFromParsed,
    subpageOrderForSerialize: () => subpageOrderForSerialize,
    trimConfigFields: () => trimConfigFields,
    validateBackupEnvelope: () => validateBackupEnvelope
  });

  // src/webserver/model/card.ts
  var CARD_CONFIG_FIELDS = [
    "entity",
    "label",
    "icon",
    "icon_on",
    "sensor",
    "unit",
    "type",
    "precision",
    "options"
  ];
  function emptyCardConfig(type) {
    return {
      entity: "",
      label: "",
      icon: "Auto",
      icon_on: "Auto",
      sensor: "",
      unit: "",
      type: type || "",
      precision: "",
      options: ""
    };
  }
  function cloneCardConfig(src) {
    const button = {
      entity: src?.entity || "",
      label: src?.label || "",
      icon: src?.icon || "Auto",
      icon_on: src?.icon_on || "Auto",
      sensor: src?.sensor || "",
      unit: src?.unit || "",
      type: src?.type || "",
      precision: src?.precision || "",
      options: src?.options || ""
    };
    if (src && Object.prototype.hasOwnProperty.call(src, "_whenOnActive")) {
      button._whenOnActive = src._whenOnActive;
    }
    if (src && Object.prototype.hasOwnProperty.call(src, "_whenOnMode")) {
      button._whenOnMode = src._whenOnMode;
    }
    return button;
  }
  function copyCardConfig(target, src) {
    const button = cloneCardConfig(src);
    for (const field of CARD_CONFIG_FIELDS) {
      target[field] = button[field];
    }
    target._whenOnActive = button._whenOnActive;
    target._whenOnMode = button._whenOnMode;
    return target;
  }
  function cardConfigChanged(before, after) {
    for (const field of CARD_CONFIG_FIELDS) {
      if ((before[field] || "") !== (after[field] || "")) return true;
    }
    return false;
  }
  function trimConfigFields(fields) {
    while (fields.length > 1 && !fields[fields.length - 1]) fields.pop();
    return fields;
  }
  function encodeConfigField(value) {
    return String(value || "").replace(/[%,;|:]/g, (ch) => {
      const hex = ch.charCodeAt(0).toString(16).toUpperCase();
      return "%" + (hex.length < 2 ? "0" : "") + hex;
    });
  }
  function decodeConfigField(value) {
    const str = String(value || "");
    return str.replace(/(%[0-9a-fA-F]{2})+/g, (run) => {
      try {
        return decodeURIComponent(run);
      } catch {
        return run;
      }
    });
  }
  function legacyButtonConfigSafe(fields) {
    return fields.join(";").charAt(0) !== "~" && fields.every((field) => {
      return String(field || "").indexOf(";") < 0;
    });
  }
  function parseRawButtonConfig(value) {
    const compact = !!(value && value.charAt(0) === "~");
    const parts = compact ? value.substring(1).split(",") : (value || "").split(";");
    const decoded = compact ? parts.map(decodeConfigField) : parts;
    return {
      entity: decoded[0] || "",
      label: decoded[1] || "",
      icon: decoded[2] || "Auto",
      icon_on: decoded[3] || "Auto",
      sensor: decoded[4] || "",
      unit: decoded[5] || "",
      type: decoded[6] || "",
      precision: decoded[7] || "",
      options: decoded[8] || ""
    };
  }

  // src/webserver/model/grid.ts
  var CARD_SIZE_SINGLE = 1;
  var CARD_SIZE_TALL = 2;
  var CARD_SIZE_WIDE = 3;
  var CARD_SIZE_LARGE = 4;
  var CARD_SIZE_EXTRA_TALL = 5;
  var CARD_SIZE_EXTRA_WIDE = 6;
  var CARD_SIZE_SINGLE_DEFINITION = {
    size: CARD_SIZE_SINGLE,
    token: "",
    rowSpan: 1,
    colSpan: 1,
    className: ""
  };
  var CARD_SIZE_DEFINITIONS = [
    CARD_SIZE_SINGLE_DEFINITION,
    { size: CARD_SIZE_TALL, token: "d", rowSpan: 2, colSpan: 1, className: "sp-btn-double" },
    { size: CARD_SIZE_WIDE, token: "w", rowSpan: 1, colSpan: 2, className: "sp-btn-wide" },
    { size: CARD_SIZE_LARGE, token: "b", rowSpan: 2, colSpan: 2, className: "sp-btn-big" },
    { size: CARD_SIZE_EXTRA_TALL, token: "t", rowSpan: 3, colSpan: 1, className: "sp-btn-extra-tall" },
    { size: CARD_SIZE_EXTRA_WIDE, token: "x", rowSpan: 1, colSpan: 3, className: "sp-btn-extra-wide" }
  ];
  function copySizes(sizes) {
    return { ...sizes || {} };
  }
  function cardSizeDefinition(size) {
    const normalized = size || CARD_SIZE_SINGLE;
    for (const definition of CARD_SIZE_DEFINITIONS) {
      if (definition.size === normalized) return definition;
    }
    return CARD_SIZE_SINGLE_DEFINITION;
  }
  function sizeFromToken(token) {
    const normalized = token || "";
    for (const definition of CARD_SIZE_DEFINITIONS) {
      if (definition.token === normalized) return definition.size;
    }
    return CARD_SIZE_SINGLE;
  }
  function sizeToken(size) {
    return cardSizeDefinition(size).token;
  }
  function sizeRowSpan(size) {
    return cardSizeDefinition(size).rowSpan;
  }
  function sizeColSpan(size) {
    return cardSizeDefinition(size).colSpan;
  }
  function cardSizeClass(size) {
    return cardSizeDefinition(size).className;
  }
  function coveredCells(pos, size, _maxSlots, gridCols, includeOrigin) {
    const cells = [];
    const rowSpan = sizeRowSpan(size);
    const colSpan = sizeColSpan(size);
    for (let r = 0; r < rowSpan; r += 1) {
      for (let c = 0; c < colSpan; c += 1) {
        if (!includeOrigin && r === 0 && c === 0) continue;
        cells.push(pos + r * gridCols + c);
      }
    }
    return cells;
  }
  function sizeFitsAt(pos, size, maxSlots, gridCols) {
    if (pos < 0 || pos >= maxSlots || gridCols <= 0) return false;
    const col = pos % gridCols;
    const row = Math.floor(pos / gridCols);
    const rows = Math.ceil(maxSlots / gridCols);
    return col + sizeColSpan(size) <= gridCols && row + sizeRowSpan(size) <= rows && pos + (sizeRowSpan(size) - 1) * gridCols + sizeColSpan(size) - 1 < maxSlots;
  }
  function markSpannedCells(grid, pos, size, maxSlots, gridCols) {
    const cells = coveredCells(pos, size, maxSlots, gridCols, false);
    for (const cell of cells) {
      if (cell >= 0 && cell < maxSlots) grid[cell] = -1;
    }
  }
  function applySpans(grid, sizes, maxSlots, gridCols) {
    for (let i = 0; i < maxSlots; i += 1) {
      const slot = grid[i] ?? 0;
      if (!(slot > 0 || slot === -2)) continue;
      const slotKey = String(slot);
      const size = sizes[slotKey] || 1;
      if (size <= 1) continue;
      if (!sizeFitsAt(i, size, maxSlots, gridCols)) {
        delete sizes[slotKey];
        continue;
      }
      const toReserve = coveredCells(i, size, maxSlots, gridCols, false);
      let ok = true;
      for (const cell of toReserve) {
        const displaced = grid[cell] ?? 0;
        if (displaced > 0 || displaced === -2) {
          let placed = false;
          for (let j = 0; j < maxSlots; j += 1) {
            if ((grid[j] ?? 0) === 0 && toReserve.indexOf(j) === -1) {
              grid[j] = displaced;
              placed = true;
              break;
            }
          }
          if (!placed) {
            ok = false;
            break;
          }
          grid[cell] = 0;
        }
      }
      if (!ok) {
        delete sizes[slotKey];
        continue;
      }
      for (const cell of toReserve) grid[cell] = -1;
    }
  }
  function parseGridOrder(order, maxSlots, gridCols, initialSizes) {
    const grid = Array(maxSlots).fill(0);
    const sizes = copySizes(initialSizes);
    if (!order || !order.trim()) return { grid, sizes };
    const parts = order.split(",");
    for (let i = 0; i < parts.length && i < maxSlots; i += 1) {
      const value = (parts[i] || "").trim();
      if (!value) continue;
      const last = value.charAt(value.length - 1);
      const parsedSize = sizeFromToken(last);
      const slot = parseInt(value, 10);
      if (slot >= 1 && slot <= maxSlots && !Number.isNaN(slot)) {
        grid[i] = slot;
        if (parsedSize > 1) sizes[String(slot)] = parsedSize;
      }
    }
    applySpans(grid, sizes, maxSlots, gridCols);
    return { grid, sizes };
  }
  function serializeGridOrder(grid, sizes) {
    let last = -1;
    for (let i = grid.length - 1; i >= 0; i -= 1) {
      if ((grid[i] ?? 0) > 0) {
        last = i;
        break;
      }
    }
    if (last < 0) return "";
    return grid.slice(0, last + 1).map((slot) => {
      if (slot <= 0) return "";
      return String(slot) + sizeToken(sizes[String(slot)]);
    }).join(",");
  }
  function clearSpans(grid, maxSlots) {
    for (let i = 0; i < maxSlots; i += 1) {
      if (grid[i] === -1) grid[i] = 0;
    }
  }

  // src/webserver/model/backup.ts
  var BACKUP_CONFIG_VERSION = 2;
  var BACKUP_FORMAT = "espcontrol.backup";
  function backupConfigError(message) {
    const err = new Error(message);
    err.backupMessage = message;
    return err;
  }
  function isRecord(value) {
    return !!value && typeof value === "object" && !Array.isArray(value);
  }
  function validateBackupEnvelope(data) {
    if (!isRecord(data)) {
      throw backupConfigError("Invalid config file - backup must be a JSON object");
    }
    const version = parseInt(String(data.version), 10);
    if (!version || version < 1) {
      throw backupConfigError("Invalid config file - missing required fields");
    }
    if (version > BACKUP_CONFIG_VERSION) {
      throw backupConfigError("Backup was created by a newer version of EspControl");
    }
    if (version >= 2 && data.format !== BACKUP_FORMAT) {
      throw backupConfigError("Invalid config file - unsupported backup format");
    }
    if (!Array.isArray(data.buttons)) {
      throw backupConfigError("Invalid config file - missing required fields");
    }
    return data;
  }
  function backupSource(data, slots) {
    const source = isRecord(data.source) ? data.source : {};
    return {
      device: String(source.device || data.device || ""),
      slots: parseInt(String(source.slots), 10) || slots || 0
    };
  }
  function createBackupEnvelope(snapshot, outputs) {
    const slots = parseInt(String(snapshot.slots), 10) || outputs.buttons.length;
    const device = snapshot.device || "";
    return {
      version: BACKUP_CONFIG_VERSION,
      format: BACKUP_FORMAT,
      device,
      source: {
        device,
        slots
      },
      exported_at: snapshot.exported_at || (/* @__PURE__ */ new Date()).toISOString(),
      button_order: outputs.button_order != null ? String(outputs.button_order) : "",
      button_on_color: snapshot.button_on_color || "0073FF",
      button_off_color: snapshot.button_off_color || "CECECE",
      sensor_card_color: snapshot.sensor_card_color || "DEDEDE",
      buttons: outputs.buttons,
      subpages: outputs.subpages,
      subpage_objects: outputs.subpage_objects || {},
      settings: snapshot.settings || {},
      screen: snapshot.screen || {}
    };
  }
  function normalizeBackupEnvelope(data, outputs) {
    return {
      version: BACKUP_CONFIG_VERSION,
      format: BACKUP_FORMAT,
      device: String(data.device || ""),
      source: backupSource(data, outputs.buttons.length),
      exported_at: String(data.exported_at || ""),
      button_order: String(data.button_order || ""),
      button_on_color: String(data.button_on_color || "0073FF"),
      button_off_color: String(data.button_off_color || "CECECE"),
      sensor_card_color: String(data.sensor_card_color || "DEDEDE"),
      buttons: outputs.buttons,
      subpages: outputs.subpages,
      subpage_objects: outputs.subpage_objects || {},
      settings: isRecord(data.settings) ? data.settings : null,
      screen: isRecord(data.screen) ? data.screen : isRecord(data.settings) && isRecord(data.settings.screen) ? data.settings.screen : null
    };
  }
  function backupOrderUsedSlots(order, importedCount) {
    const parts = String(order || "").split(",");
    const usedSlots = [];
    const seen = {};
    for (const part of parts) {
      const token = part.trim();
      if (!token) continue;
      const lastCh = token.charAt(token.length - 1);
      const parsedSize = sizeFromToken(lastCh);
      const num = parseInt(token, 10);
      if (Number.isNaN(num) || num < 1 || num > importedCount || seen[String(num)]) continue;
      seen[String(num)] = true;
      usedSlots.push({ oldSlot: num, size: parsedSize });
    }
    return { usedSlots, seen };
  }
  function backupPlaceSlotAt(grid, slot, pos, size, maxSlots, gridCols) {
    grid[pos] = slot;
    if (size > 1) {
      markSpannedCells(grid, pos, size, maxSlots, gridCols);
    }
  }
  function planBackupButtonLayout(sourceButtons, buttonOrder, targetSlots, gridCols) {
    const importedCount = sourceButtons.length;
    const buttons = [];
    const importedSizes = {};
    const slotMap = {};
    let orderStr = "";
    if (importedCount !== targetSlots) {
      const orderInfo = backupOrderUsedSlots(buttonOrder, importedCount);
      const usedSlots = orderInfo.usedSlots;
      const seen = orderInfo.seen;
      for (let j = 0; j < importedCount; j += 1) {
        const slotNum = j + 1;
        if (seen[String(slotNum)]) continue;
        const button = sourceButtons[j] || emptyCardConfig();
        if (button.entity || button.label || button.type) {
          usedSlots.push({ oldSlot: slotNum, size: 1 });
        }
      }
      const limit = Math.min(usedSlots.length, targetSlots);
      for (let u = 0; u < limit; u += 1) {
        const newSlot = u + 1;
        const used = usedSlots[u];
        if (!used) continue;
        slotMap[String(used.oldSlot)] = newSlot;
        buttons.push(cloneCardConfig(sourceButtons[used.oldSlot - 1] || emptyCardConfig()));
        if (used.size > 1) importedSizes[String(newSlot)] = used.size;
      }
      for (let fill = limit; fill < targetSlots; fill += 1) {
        buttons.push(emptyCardConfig());
      }
      const newGrid = Array(targetSlots).fill(0);
      let pos = 0;
      for (let p = 0; p < limit && pos < targetSlots; p += 1) {
        const newSlot = p + 1;
        let targetSize = importedSizes[String(newSlot)] || 1;
        if (!sizeFitsAt(pos, targetSize, targetSlots, gridCols)) {
          targetSize = 1;
          delete importedSizes[String(newSlot)];
        }
        backupPlaceSlotAt(newGrid, newSlot, pos, targetSize, targetSlots, gridCols);
        pos += 1;
        while (pos < targetSlots && newGrid[pos] === -1) pos += 1;
      }
      orderStr = serializeGridOrder(newGrid, importedSizes);
    } else {
      for (let i = 0; i < targetSlots; i += 1) {
        buttons.push(cloneCardConfig(i < importedCount ? sourceButtons[i] : emptyCardConfig()));
        slotMap[String(i + 1)] = i + 1;
      }
      orderStr = String(buttonOrder || "");
    }
    return {
      importedCount,
      buttons,
      button_order: orderStr,
      importedSizes,
      slotMap
    };
  }

  // src/webserver/model/subpage.ts
  var BACK_TOKENS = /* @__PURE__ */ new Set(["B", "Bd", "Bw", "Bb", "Bt", "Bx"]);
  function isRecord2(value) {
    return !!value && typeof value === "object" && !Array.isArray(value);
  }
  function stringField(record, key, fallback = "") {
    const value = record[key];
    return value == null ? fallback : String(value || fallback);
  }
  function isBackOrderToken(token) {
    return BACK_TOKENS.has(String(token || ""));
  }
  function parseBackOrderToken(value) {
    const raw = String(value || "").trim();
    const eq = raw.indexOf("=");
    const token = eq >= 0 ? raw.substring(0, eq) : raw;
    const label = eq >= 0 ? decodeConfigField(raw.substring(eq + 1)) : "Back";
    if (!BACK_TOKENS.has(token)) {
      return { token: raw, label: "Back" };
    }
    return { token, label: label || "Back" };
  }
  function backOrderToken(baseToken, label) {
    const token = parseBackOrderToken(baseToken).token;
    const text = label || "Back";
    return text === "Back" ? token : token + "=" + encodeConfigField(text);
  }
  function backLabelFromOrder(order) {
    for (const item of order || []) {
      const parsed = parseBackOrderToken(item);
      if (BACK_TOKENS.has(parsed.token)) {
        return parsed.label || "Back";
      }
    }
    return "Back";
  }
  function parseSubpageOrder(orderStr) {
    const order = [];
    let backLabel = "Back";
    if (orderStr) {
      const parts = orderStr.split(",");
      for (const part of parts) {
        const parsed = parseBackOrderToken(part);
        order.push(parsed.token);
        if (BACK_TOKENS.has(parsed.token)) {
          backLabel = parsed.label || "Back";
        }
      }
    }
    return { order, backLabel };
  }
  function subpageOrderForSerialize(order, backLabel) {
    const out = [];
    for (const item of order || []) {
      const parsed = parseBackOrderToken(item);
      if (BACK_TOKENS.has(parsed.token)) {
        out.push(backOrderToken(parsed.token, backLabel || parsed.label || "Back"));
      } else {
        out.push(parsed.token);
      }
    }
    return out;
  }
  function parseLegacySubpageConfig(value) {
    if (!value || !value.trim()) return { order: [], buttons: [], backLabel: "Back" };
    const parts = value.split("|");
    const parsedOrder = parseSubpageOrder(parts[0] || "");
    const buttons = [];
    for (let i = 1; i < parts.length; i += 1) {
      const fields = (parts[i] || "").split(":");
      buttons.push({
        entity: fields[0] || "",
        label: fields[1] || "",
        icon: fields[2] || "Auto",
        icon_on: fields[3] || "Auto",
        sensor: fields[4] || "",
        unit: fields[5] || "",
        type: fields[6] || "",
        precision: fields[7] || "",
        options: fields[8] || ""
      });
    }
    return {
      order: parsedOrder.order,
      buttons,
      backLabel: parsedOrder.backLabel
    };
  }
  function parseCompactSubpageConfig(value, typeFromCode) {
    if (!value || value.length < 2) return { order: [], buttons: [], backLabel: "Back" };
    const parts = value.substring(1).split("|");
    const parsedOrder = parseSubpageOrder(parts[0] || "");
    const buttons = [];
    for (let i = 1; i < parts.length; i += 1) {
      const fields = (parts[i] || "").split(",");
      buttons.push({
        type: typeFromCode(fields[0] || ""),
        entity: decodeConfigField(fields[1]),
        label: decodeConfigField(fields[2]),
        icon: decodeConfigField(fields[3]) || "Auto",
        icon_on: decodeConfigField(fields[4]) || "Auto",
        sensor: decodeConfigField(fields[5]),
        unit: decodeConfigField(fields[6]),
        precision: decodeConfigField(fields[7]),
        options: decodeConfigField(fields[8])
      });
    }
    return {
      order: parsedOrder.order,
      buttons,
      backLabel: parsedOrder.backLabel
    };
  }
  function parseRawSubpageConfig(value, typeFromCode) {
    if (value && value.charAt(0) === "~") return parseCompactSubpageConfig(value, typeFromCode);
    return parseLegacySubpageConfig(value);
  }
  function structuredSubpageFromParsed(subpage) {
    return {
      order: (subpage?.order || []).map((item) => parseBackOrderToken(item).token),
      back_label: subpage?.backLabel || backLabelFromOrder(subpage?.order) || "Back",
      buttons: (subpage?.buttons || []).map((button) => cloneCardConfig(button))
    };
  }
  function parseStructuredSubpageConfig(value) {
    if (!isRecord2(value)) return { order: [], buttons: [], backLabel: "Back" };
    const orderValues = Array.isArray(value.order) ? value.order.map((item) => String(item || "")) : [];
    const parsedOrder = parseSubpageOrder(orderValues.join(","));
    const backLabel = stringField(value, "back_label", stringField(value, "backLabel", parsedOrder.backLabel));
    const rawButtons = Array.isArray(value.buttons) ? value.buttons : [];
    const buttons = rawButtons.map((button) => {
      const record = isRecord2(button) ? button : {};
      return cloneCardConfig({
        entity: stringField(record, "entity"),
        label: stringField(record, "label"),
        icon: stringField(record, "icon", "Auto"),
        icon_on: stringField(record, "icon_on", "Auto"),
        sensor: stringField(record, "sensor"),
        unit: stringField(record, "unit"),
        type: stringField(record, "type"),
        precision: stringField(record, "precision"),
        options: stringField(record, "options")
      });
    });
    return {
      order: parsedOrder.order,
      buttons,
      backLabel: backLabel || "Back"
    };
  }
  function legacySubpageFieldsSafe(buttonFields) {
    for (const fields of buttonFields) {
      for (const field of fields) {
        const value = String(field || "");
        if (value.indexOf("|") >= 0 || value.indexOf(":") >= 0) return false;
      }
    }
    return true;
  }
  function serializeLegacySubpageConfig(order, buttonFields) {
    if (!buttonFields.length) return order.join(",");
    let out = order.join(",");
    for (const fields of buttonFields) {
      out += "|" + fields.join(":");
    }
    return out;
  }
  function serializeCompactSubpageConfig(order, buttonFields) {
    if (!buttonFields.length) return "";
    let out = "~" + order.join(",");
    for (const fields of buttonFields) {
      out += "|" + fields.join(",");
    }
    return out;
  }
  function chooseSerializedSubpageConfig(order, buttonCount, legacy, compact) {
    if (!buttonCount && order.length > 0) return order.join(",");
    if (!compact) return legacy;
    if (!legacy) return compact;
    return compact.length < legacy.length ? compact : legacy;
  }
  function utf8ByteLength(str) {
    let bytes = 0;
    for (let i = 0; i < str.length; i++) {
      const code = str.charCodeAt(i);
      if (code < 128) bytes += 1;
      else if (code >= 55296 && code <= 56319) {
        bytes += 4;
        i += 1;
      } else if (code < 2048) bytes += 2;
      else bytes += 3;
    }
    return bytes;
  }
  function splitSubpageConfigChunks(value, chunkCount, chunkSize = 255) {
    const full = String(value || "");
    if (chunkCount < 1 || chunkSize < 1 || utf8ByteLength(full) > chunkCount * chunkSize) return null;
    const chunks = [];
    let charPos = 0;
    for (let i = 0; i < chunkCount; i += 1) {
      let bytes = 0;
      let end = charPos;
      while (end < full.length) {
        const code = full.charCodeAt(end);
        const charBytes = code < 128 ? 1 : code >= 55296 && code <= 56319 ? 4 : code < 2048 ? 2 : 3;
        if (bytes + charBytes > chunkSize) break;
        bytes += charBytes;
        end += code >= 55296 && code <= 56319 ? 2 : 1;
      }
      chunks.push(full.substring(charPos, end));
      charPos = end;
    }
    return chunks;
  }
  function buildSubpageGrid(subpage, maxSlots, gridCols) {
    const grid = Array(maxSlots).fill(0);
    const sizes = { ...subpage.sizes || {} };
    const order = subpage.order || [];
    const buttonCount = (subpage.buttons || []).length;
    if (order.length > 0) {
      const hasBack = order.some((item) => isBackOrderToken(parseBackOrderToken(item).token));
      if (hasBack) {
        for (let i = 0; i < order.length && i < maxSlots; i += 1) {
          const token = parseBackOrderToken(order[i]).token;
          if (!token) continue;
          if (isBackOrderToken(token)) {
            grid[i] = -2;
            const backSize = sizeFromToken(token.charAt(1));
            if (backSize > 1) sizes[String(-2)] = backSize;
            else delete sizes[String(-2)];
            continue;
          }
          const last = token.charAt(token.length - 1);
          const parsedSize = sizeFromToken(last);
          const slot = parseInt(token, 10);
          if (slot >= 1 && slot <= buttonCount && !Number.isNaN(slot)) {
            grid[i] = slot;
            if (parsedSize > 1) sizes[String(slot)] = parsedSize;
          }
        }
      } else {
        grid[0] = -2;
        delete sizes[String(-2)];
        for (let i = 0; i < order.length && i + 1 < maxSlots; i += 1) {
          const token = parseBackOrderToken(order[i]).token;
          if (!token) continue;
          const last = token.charAt(token.length - 1);
          const parsedSize = sizeFromToken(last);
          const slot = parseInt(token, 10);
          if (slot >= 1 && slot <= buttonCount && !Number.isNaN(slot)) {
            grid[i + 1] = slot;
            if (parsedSize > 1) sizes[String(slot)] = parsedSize;
          }
        }
      }
    } else {
      grid[0] = -2;
      delete sizes[String(-2)];
    }
    applySpans(grid, sizes, maxSlots, gridCols);
    return { grid, sizes };
  }
  function serializeSubpageGrid(grid, sizes, backLabel) {
    let last = -1;
    for (let i = grid.length - 1; i >= 0; i -= 1) {
      const slot = grid[i] ?? 0;
      if (slot > 0 || slot === -2) {
        last = i;
        break;
      }
    }
    if (last < 0) return [];
    const order = [];
    for (let i = 0; i <= last; i += 1) {
      const slot = grid[i] ?? 0;
      if (slot === -2) {
        order.push(backOrderToken("B" + sizeToken(sizes[String(-2)]), backLabel || "Back"));
      } else if (slot <= 0) {
        order.push("");
      } else {
        order.push(String(slot) + sizeToken(sizes[String(slot)]));
      }
    }
    return order;
  }

  // src/webserver/model/settings.ts
  function normalizeTemperatureUnit(value) {
    const unit = String(value == null ? "" : value).trim().toLowerCase();
    if (unit === "f" || unit === "\xB0f" || unit === "fahrenheit") return "\xB0F";
    if (unit === "c" || unit === "\xB0c" || unit === "celsius" || unit === "centigrade") return "\xB0C";
    return "Auto";
  }
  function normalizeClockBarTemperatureEntities(value) {
    const input = Array.isArray(value) ? value : String(value || "").split(/[|,\n]/);
    const out = [];
    for (const entry of input) {
      const entity = String(entry || "").trim();
      if (entity && out.indexOf(entity) === -1) out.push(entity);
    }
    return out.slice(0, 1);
  }
  var CLOCK_BAR_FIXED_LAYOUT = "left:temperature|middle:time|right:network";
  function normalizeLanguage(value) {
    const language = String(value == null ? "" : value).trim().toLowerCase();
    return language || "en";
  }
  function normalizeHour(value, fallback) {
    const n = parseInt(String(value), 10);
    if (!Number.isFinite(n)) return fallback;
    if (n < 0) return 0;
    if (n > 23) return 23;
    return n;
  }
  function normalizeTimeOfDay(value, fallback) {
    const text = String(value == null ? "" : value).trim();
    const match = /^(\d{1,2}):(\d{2})$/.exec(text);
    if (!match) return fallback;
    const hour = parseInt(match[1] || "", 10);
    const minute = parseInt(match[2] || "", 10);
    if (!Number.isFinite(hour) || !Number.isFinite(minute)) return fallback;
    if (hour < 0 || hour > 23 || minute < 0 || minute > 59) return fallback;
    return String(hour).padStart(2, "0") + ":" + String(minute).padStart(2, "0");
  }
  function normalizeScheduleWakeTimeout(value) {
    const n = parseFloat(String(value));
    if (!Number.isFinite(n) || n <= 0) return 60;
    if (n < 10) return 10;
    if (n > 3600) return 3600;
    return Math.round(n);
  }
  function normalizeScheduleWakeBrightness(value) {
    const n = parseFloat(String(value));
    if (!Number.isFinite(n) || n <= 0) return 10;
    if (n < 10) return 10;
    if (n > 100) return 100;
    return Math.round(n);
  }
  function normalizeScheduleClockBrightness(value) {
    const n = parseFloat(String(value));
    if (!Number.isFinite(n) || n <= 0) return 10;
    if (n < 1) return 1;
    if (n > 100) return 100;
    return Math.round(n);
  }
  function normalizeHexColor(value, fallback) {
    const color = String(value == null ? "" : value).replace(/^#/, "").trim().toUpperCase();
    return /^[0-9A-F]{6}$/.test(color) ? color : fallback;
  }
  function normalizeScheduleDimmedBrightness(value) {
    const n = parseFloat(String(value));
    if (!Number.isFinite(n) || n <= 0) return 10;
    if (n < 1) return 1;
    if (n > 100) return 100;
    return Math.round(n);
  }
  function normalizeScheduleMode(value) {
    const mode = String(value || "").toLowerCase().replace(/[\s-]+/g, "_");
    if (mode === "screen_dimmed" || mode === "dimmed" || mode === "always_on" || mode === "always") {
      return "screen_dimmed";
    }
    if (mode === "clock") return "clock";
    return "screen_off";
  }
  function normalizeScheduleTrigger(value, scheduleEnabled = false) {
    const trigger = String(value || "").toLowerCase().replace(/[\s-]+/g, "_");
    if (trigger === "sensor") return "sensor";
    if (trigger === "time" || trigger === "timer") return "time";
    if (trigger === "disabled" || trigger === "off") return "disabled";
    return scheduleEnabled ? "time" : "disabled";
  }
  function normalizeScreensaverAction(value) {
    const action = String(value || "").toLowerCase().replace(/[\s-]+/g, "_");
    if (action === "screen_dimmed" || action === "dimmed" || action === "dim") return "dim";
    if (action === "clock") return "clock";
    return "off";
  }
  function screensaverActionOption(value) {
    const action = normalizeScreensaverAction(value);
    if (action === "dim") return "Screen Dimmed";
    if (action === "clock") return "Clock";
    return "Display Off";
  }
  function scheduleModeOption(value) {
    const mode = normalizeScheduleMode(value);
    if (mode === "screen_dimmed") return "Screen Dimmed";
    if (mode === "clock") return "Clock";
    return "Screen off";
  }
  function normalizeClockBrightness(value, fallback) {
    const n = parseFloat(String(value));
    if (!Number.isFinite(n) || n <= 0) return fallback;
    if (n < 1) return 1;
    if (n > 100) return 100;
    return Math.round(n);
  }
  function normalizeScreensaverDimmedBrightness(value) {
    const n = parseFloat(String(value));
    if (!Number.isFinite(n) || n <= 0) return 10;
    if (n < 1) return 1;
    if (n > 100) return 100;
    return Math.round(n);
  }
  function normalizeNtpServer(value, fallback) {
    const server = String(value == null ? "" : value).trim();
    return server || fallback;
  }
  function numberOrFallback(value, fallback) {
    const n = parseFloat(String(value));
    return Number.isFinite(n) ? n : fallback;
  }
  function objectValue(source, key) {
    return Object.prototype.hasOwnProperty.call(source, key) ? source[key] : void 0;
  }
  function normalizeBackupScreenSettings(screenSettings, current) {
    const legacyScheduleEnabled = !!screenSettings.schedule_enabled;
    const scheduleTrigger = normalizeScheduleTrigger(screenSettings.schedule_trigger, legacyScheduleEnabled);
    return {
      brightnessDayVal: numberOrFallback(screenSettings.brightness_day, 100),
      brightnessNightVal: numberOrFallback(screenSettings.brightness_night, 75),
      automaticBrightnessEnabled: objectValue(screenSettings, "automatic_brightness") != null ? !!screenSettings.automatic_brightness : true,
      brightnessDawnTime: normalizeTimeOfDay(screenSettings.brightness_dawn_time, "06:00"),
      brightnessDuskTime: normalizeTimeOfDay(screenSettings.brightness_dusk_time, "18:00"),
      scheduleTrigger,
      scheduleEnabled: scheduleTrigger !== "disabled",
      scheduleOnHour: normalizeHour(screenSettings.schedule_on_hour, 6),
      scheduleOffHour: normalizeHour(screenSettings.schedule_off_hour, 23),
      scheduleMode: normalizeScheduleMode(screenSettings.schedule_mode),
      scheduleWakeTimeout: normalizeScheduleWakeTimeout(screenSettings.schedule_wake_timeout),
      scheduleWakeBrightness: normalizeScheduleWakeBrightness(
        objectValue(screenSettings, "schedule_wake_brightness") != null ? screenSettings.schedule_wake_brightness : current.scheduleWakeBrightness
      ),
      scheduleDimmedBrightness: normalizeScheduleDimmedBrightness(
        objectValue(screenSettings, "schedule_dimmed_brightness") != null ? screenSettings.schedule_dimmed_brightness : current.scheduleDimmedBrightness
      ),
      scheduleClockBrightness: normalizeScheduleClockBrightness(
        objectValue(screenSettings, "schedule_clock_brightness") != null ? screenSettings.schedule_clock_brightness : current.scheduleClockBrightness
      ),
      scheduleClockTextColor: normalizeHexColor(
        objectValue(screenSettings, "schedule_clock_text_color") != null ? screenSettings.schedule_clock_text_color : current.scheduleClockTextColor,
        "FFFFFF"
      )
    };
  }
  function normalizeScreensaverMode(value) {
    const mode = String(value || "disabled");
    return mode === "sensor" || mode === "timer" || mode === "disabled" ? mode : "disabled";
  }
  function normalizeScreenRotationValue(value, options) {
    const rotation = String(value == null ? "" : value);
    return options.indexOf(rotation) !== -1 ? rotation : "0";
  }
  function normalizeBackupPanelSettings(settings, current) {
    const hasNtpServer1 = objectValue(settings, "ntp_server_1") !== void 0;
    const hasNtpServer2 = objectValue(settings, "ntp_server_2") !== void 0;
    const hasNtpServer3 = objectValue(settings, "ntp_server_3") !== void 0;
    const hasOutdoorTempEnable = objectValue(settings, "outdoor_temp_enable") !== void 0;
    const clockFormat = current.clockFormatOptions.indexOf(String(settings.clock_format || "")) !== -1 ? String(settings.clock_format) : current.clockFormat;
    const screensaverAction = normalizeScreensaverAction(
      objectValue(settings, "screensaver_action") != null ? settings.screensaver_action : settings.clock_screensaver ? "clock" : "off"
    );
    const clockBrightnessDay = normalizeClockBrightness(
      objectValue(settings, "clock_brightness_day") != null ? settings.clock_brightness_day : settings.clock_brightness,
      35
    );
    const clockBrightnessNight = normalizeClockBrightness(
      objectValue(settings, "clock_brightness_night") != null ? settings.clock_brightness_night : settings.clock_brightness,
      clockBrightnessDay
    );
    const legacyTemperatureEntities = [];
    if (settings.outdoor_temp_enable && settings.outdoor_temp_entity) {
      legacyTemperatureEntities.push(String(settings.outdoor_temp_entity));
    }
    if (settings.indoor_temp_enable && settings.indoor_temp_entity) {
      legacyTemperatureEntities.push(String(settings.indoor_temp_entity));
    }
    const clockBarTemperatureEntities = normalizeClockBarTemperatureEntities(
      objectValue(settings, "clock_bar_temperature_entities") != null ? settings.clock_bar_temperature_entities : legacyTemperatureEntities
    );
    return {
      indoorTempEnable: false,
      outdoorTempEnable: hasOutdoorTempEnable ? !!settings.outdoor_temp_enable : clockBarTemperatureEntities.length > 0,
      indoorTempEntity: "",
      outdoorTempEntity: clockBarTemperatureEntities[0] || "",
      clockBarTemperatureEntities,
      clockBar: objectValue(settings, "clock_bar") != null ? !!settings.clock_bar : false,
      clockBarLayout: CLOCK_BAR_FIXED_LAYOUT,
      clockBarTime: objectValue(settings, "clock_bar_time") != null ? !!settings.clock_bar_time : true,
      networkStatusIcon: objectValue(settings, "network_status_icon") != null ? !!settings.network_status_icon : true,
      temperatureDegreeSymbol: objectValue(settings, "temperature_degree_symbol") != null ? !!settings.temperature_degree_symbol : true,
      subpageChevron: objectValue(settings, "subpage_chevron") != null ? !!settings.subpage_chevron : true,
      timezone: String(settings.timezone || current.timezone),
      temperatureUnit: normalizeTemperatureUnit(settings.temperature_unit),
      language: normalizeLanguage(settings.language || current.language),
      clockFormat,
      hasNtpServer1,
      hasNtpServer2,
      hasNtpServer3,
      ntpServer1: hasNtpServer1 ? normalizeNtpServer(settings.ntp_server_1, current.ntpDefaults[0] || "") : current.ntpServer1,
      ntpServer2: hasNtpServer2 ? normalizeNtpServer(settings.ntp_server_2, current.ntpDefaults[1] || "") : current.ntpServer2,
      ntpServer3: hasNtpServer3 ? normalizeNtpServer(settings.ntp_server_3, current.ntpDefaults[2] || "") : current.ntpServer3,
      screensaverMode: normalizeScreensaverMode(settings.screensaver_mode),
      presenceSensorEntity: String(settings.presence_sensor_entity || ""),
      mediaPlayerSleepPrevention: !!settings.media_player_sleep_prevention,
      mediaPlayerSleepPreventionEntity: String(settings.media_player_sleep_prevention_entity || ""),
      coverArtScreensaver: !!settings.cover_art_screensaver,
      coverArtMediaPlayerEntity: String(settings.cover_art_media_player_entity || settings.media_player_sleep_prevention_entity || ""),
      coverArtAttributeConditions: String(settings.cover_art_attribute_conditions || settings.cover_art_conditions || ""),
      coverArtDelay: objectValue(settings, "cover_art_delay") != null ? settings.cover_art_delay : 10,
      coverArtTrackOverlayDuration: objectValue(settings, "cover_art_track_overlay_duration") != null ? settings.cover_art_track_overlay_duration : 5,
      coverArtHideExternalInput: objectValue(settings, "cover_art_hide_external_input") != null ? !!settings.cover_art_hide_external_input : true,
      screensaverAction,
      clockScreensaver: screensaverAction === "clock",
      clockBrightnessDay,
      clockBrightnessNight,
      screensaverDimmedBrightness: normalizeScreensaverDimmedBrightness(settings.screensaver_dimmed_brightness),
      screensaverTimeout: settings.screensaver_timeout || 300,
      homeScreenTimeout: objectValue(settings, "home_screen_timeout") != null ? settings.home_screen_timeout : 60,
      screenRotation: normalizeScreenRotationValue(settings.screen_rotation, current.screenRotationOptions)
    };
  }
  return __toCommonJS(index_exports);
})();
