#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG CLIMATE HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

template<typename Config, typename FieldHook, typename OptionHook>
inline bool normalize_saved_config_climate(Config &config, FieldHook normalize_fields,
                                           OptionHook normalize_options) {
  if (config.type != "climate" && config.type != "climate_control") return false;
  normalize_fields(config);
    config.sensor.clear();
    config.unit.clear();
    if (config.type == "climate") config.type = "climate_control";
  config.options = normalize_options(config.options, config);
  return true;
}
