#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG OCCUPANCY HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

template<typename Config, typename FieldHook, typename OptionHook>
inline bool normalize_saved_config_occupancy(Config &config, FieldHook normalize_fields,
                                             OptionHook normalize_options) {
  if (config.type == "door_window") {
    config.entity.clear();
    normalize_fields(config);
    config.unit.clear();
    config.type = "door_window";
    config.options = normalize_options(config.options, config);
    return true;
  }
  if (config.type == "presence") {
    config.entity.clear();
    normalize_fields(config);
    config.unit.clear();
    config.type = "presence";
    config.precision.clear();
    config.options = normalize_options(config.options, config);
    return true;
  }
  return false;
}
