#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG VACUUM HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

#include <string>

inline std::string normalize_saved_config_vacuum_sensor(const std::string &sensor) {
  if (sensor == "vacuum.start") return "start_stop";
  if (sensor == "vacuum.return_to_base") return "dock";
  return sensor == "status" || sensor == "start_stop" || sensor == "dock" || sensor == "pause_resume" || sensor == "clean_spot" || sensor == "locate" || sensor == "clean_area" ? sensor : "start_stop";
}

inline std::string normalize_saved_config_vacuum_icon_on(const std::string &) {
  return "Auto";
}

inline std::string normalize_saved_config_vacuum_precision(const std::string &) {
  return "";
}

inline std::string normalize_saved_config_vacuum_options(const std::string &) {
  return "";
}
