#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG LIGHT CONTROL HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

template<typename Config, typename OptionHook>
inline bool normalize_saved_config_light_control(Config &config,
                                                 OptionHook normalize_options) {
  if (config.type != "light_control") return false;
    config.sensor.clear();
    config.unit.clear();
    config.type = "light_control";
    config.precision.clear();
  config.options = normalize_options(config.options, config);
  return true;
}
