#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG SENSOR HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

template<typename Config>
inline bool migrate_saved_config_sensor_legacy(Config &config) {
  if (config.type == "local_sensor") {
    config.type = "sensor";
    config.sensor = "local";
    config.icon_on = "Auto";
    config.options = "";
    return true;
  }
  if (config.type == "text_sensor") {
    config.type = "sensor";
    config.entity = "";
    config.label = "";
    config.unit = "";
    config.precision = "text";
    config.icon_on = "Auto";
    return true;
  }
  return false;
}

template<typename Config, typename FieldHook, typename OptionHook>
inline bool normalize_saved_config_sensor(Config &config, bool was_legacy_text_sensor,
                                          FieldHook normalize_fields, OptionHook normalize_options) {
  if (config.type != "sensor") return false;
  normalize_fields(config, was_legacy_text_sensor);
  config.options = normalize_options(config.options, config.precision);
  return true;
}
