#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG DATE/TIME HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

template<typename Config, typename FieldHook, typename OptionHook>
inline bool normalize_saved_config_date_time(Config &config, FieldHook normalize_fields,
                                            OptionHook normalize_options) {
  if (config.type == "calendar") {
    normalize_fields(config);
    config.label.clear();
    config.icon = "Auto";
    config.icon_on = "Auto";
    config.sensor.clear();
    config.unit.clear();
    config.type = "calendar";
    if (config.precision != "" && config.precision != "datetime") config.precision = "";
    config.options = normalize_options(config.options, config);
    return true;
  }
  if (config.type == "clock") {
    config.entity.clear();
    config.label.clear();
    config.icon = "Auto";
    config.icon_on = "Auto";
    config.sensor.clear();
    config.unit.clear();
    config.type = "clock";
    config.precision.clear();
    config.options = normalize_options(config.options, config);
    return true;
  }
  if (config.type == "timezone") {
    normalize_fields(config);
    config.label.clear();
    config.icon = "Auto";
    config.icon_on = "Auto";
    config.sensor.clear();
    config.unit.clear();
    config.type = "timezone";
    config.precision.clear();
    config.options = normalize_options(config.options, config);
    return true;
  }
  return false;
}
