#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG ACCESS HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

template<typename Config, typename FieldHook, typename OptionHook>
inline bool normalize_saved_config_access(Config &config, FieldHook normalize_fields,
                                          OptionHook normalize_options) {
  if (config.type == "cover") {
    normalize_fields(config);
    config.type = "cover";
    config.precision.clear();
    config.options = normalize_options(config.options, config);
    return true;
  }
  if (config.type == "garage") {
    normalize_fields(config);
    config.unit.clear();
    config.type = "garage";
    config.precision.clear();
    config.options = normalize_options(config.options, config);
    return true;
  }
  if (config.type == "gate") {
    normalize_fields(config);
    config.unit.clear();
    config.type = "gate";
    config.precision.clear();
    config.options = normalize_options(config.options, config);
    return true;
  }
  if (config.type == "lock") {
    normalize_fields(config);
    config.unit.clear();
    config.type = "lock";
    config.precision.clear();
    config.options.clear();
    return true;
  }
  return false;
}
