#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG SHADOW HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// Test-only shadow code: production firmware does not include this header.
// =============================================================================

#include <cstddef>
#include <string>

enum class CardContractShadowPolicyKind { KEEP, CLEAR, DEFAULT_VALUE, ALLOWED, ALIAS, HOOK };
struct CardContractShadowFieldPolicy { const char *field; CardContractShadowPolicyKind policy; const char *detail; };

inline const CardContractShadowFieldPolicy SAVED_CONFIG_SHADOW_ACTION_FIELDS[] = {
  {"entity", CardContractShadowPolicyKind::KEEP, ""},
  {"label", CardContractShadowPolicyKind::KEEP, ""},
  {"icon", CardContractShadowPolicyKind::HOOK, "normalize_action_fields"},
  {"icon_on", CardContractShadowPolicyKind::HOOK, "normalize_action_fields"},
  {"sensor", CardContractShadowPolicyKind::HOOK, "normalize_action_fields"},
  {"unit", CardContractShadowPolicyKind::HOOK, "normalize_action_fields"},
  {"type", CardContractShadowPolicyKind::HOOK, "normalize_action_fields"},
  {"precision", CardContractShadowPolicyKind::HOOK, "normalize_action_fields"},
  {"options", CardContractShadowPolicyKind::HOOK, "normalize_action_options"},
};

inline const CardContractShadowFieldPolicy SAVED_CONFIG_SHADOW_SENSOR_FIELDS[] = {
  {"entity", CardContractShadowPolicyKind::KEEP, ""},
  {"label", CardContractShadowPolicyKind::KEEP, ""},
  {"icon", CardContractShadowPolicyKind::HOOK, "normalize_sensor_fields"},
  {"icon_on", CardContractShadowPolicyKind::HOOK, "normalize_sensor_fields"},
  {"sensor", CardContractShadowPolicyKind::HOOK, "normalize_sensor_fields"},
  {"unit", CardContractShadowPolicyKind::KEEP, ""},
  {"type", CardContractShadowPolicyKind::DEFAULT_VALUE, "sensor"},
  {"precision", CardContractShadowPolicyKind::HOOK, "normalize_sensor_fields"},
  {"options", CardContractShadowPolicyKind::HOOK, "normalize_sensor_options"},
};

inline const CardContractShadowFieldPolicy SAVED_CONFIG_SHADOW_MEDIA_FIELDS[] = {
  {"entity", CardContractShadowPolicyKind::KEEP, ""},
  {"label", CardContractShadowPolicyKind::HOOK, "normalize_media_fields"},
  {"icon", CardContractShadowPolicyKind::HOOK, "normalize_media_fields"},
  {"icon_on", CardContractShadowPolicyKind::KEEP, ""},
  {"sensor", CardContractShadowPolicyKind::HOOK, "normalize_media_fields"},
  {"unit", CardContractShadowPolicyKind::KEEP, ""},
  {"type", CardContractShadowPolicyKind::DEFAULT_VALUE, "media"},
  {"precision", CardContractShadowPolicyKind::HOOK, "normalize_media_fields"},
  {"options", CardContractShadowPolicyKind::HOOK, "normalize_media_options"},
};

inline const CardContractShadowFieldPolicy SAVED_CONFIG_SHADOW_VACUUM_FIELDS[] = {
  {"entity", CardContractShadowPolicyKind::KEEP, ""},
  {"label", CardContractShadowPolicyKind::KEEP, ""},
  {"icon", CardContractShadowPolicyKind::HOOK, "normalize_vacuum_fields"},
  {"icon_on", CardContractShadowPolicyKind::DEFAULT_VALUE, "Auto"},
  {"sensor", CardContractShadowPolicyKind::ALLOWED, "start_stop"},
  {"unit", CardContractShadowPolicyKind::HOOK, "normalize_vacuum_fields"},
  {"type", CardContractShadowPolicyKind::DEFAULT_VALUE, "vacuum"},
  {"precision", CardContractShadowPolicyKind::CLEAR, ""},
  {"options", CardContractShadowPolicyKind::CLEAR, ""},
};

inline const char *const SAVED_CONFIG_SHADOW_VACUUM_MODES[] = {"status", "start_stop", "dock", "pause_resume", "clean_spot", "locate", "clean_area"};
inline const char *const SAVED_CONFIG_SHADOW_VACUUM_UNIT_MODES[] = {"clean_area"};
inline const char *const SAVED_CONFIG_SHADOW_ACTION_OPTION_SELECT_ACTIONS[] = {"input_select.select_option", "select.select_option"};

inline bool saved_config_shadow_string_in(const std::string &value, const char *const *values, size_t count) {
  for (size_t index = 0; index < count; ++index) if (value == values[index]) return true;
  return false;
}

inline const char *saved_config_shadow_vacuum_icon(const std::string &mode) {
  if (mode == "dock") return "Robot Vacuum Variant";
  if (mode == "clean_spot") return "Vacuum";
  if (mode == "locate") return "Robot Vacuum Alert";
  if (mode == "clean_area") return "Vacuum Outline";
  return "Robot Vacuum";
}

template<typename Config>
inline bool normalize_saved_config_vacuum_shadow(Config &config) {
  if (config.type == "action" && config.sensor == "vacuum.start") { config.type = "vacuum"; config.sensor = "start_stop"; }
  if (config.type == "action" && config.sensor == "vacuum.return_to_base") { config.type = "vacuum"; config.sensor = "dock"; }
  if (config.type != "vacuum") return false;
  if (!saved_config_shadow_string_in(config.sensor, SAVED_CONFIG_SHADOW_VACUUM_MODES, sizeof(SAVED_CONFIG_SHADOW_VACUUM_MODES) / sizeof(SAVED_CONFIG_SHADOW_VACUUM_MODES[0]))) config.sensor = "start_stop";
  config.type = "vacuum"; config.icon_on = "Auto"; config.precision.clear(); config.options.clear();
  if (!saved_config_shadow_string_in(config.sensor, SAVED_CONFIG_SHADOW_VACUUM_UNIT_MODES, sizeof(SAVED_CONFIG_SHADOW_VACUUM_UNIT_MODES) / sizeof(SAVED_CONFIG_SHADOW_VACUUM_UNIT_MODES[0]))) config.unit.clear();
  if (config.icon.empty() || config.icon == "Auto") config.icon = saved_config_shadow_vacuum_icon(config.sensor);
  return true;
}

inline void saved_config_shadow_append_option(std::string &out, const std::string &name, const std::string &value = "") {
  if (!out.empty()) out += ',';
  out += name;
  if (!value.empty()) out += "=" + encode_compact_field(value);
}

template<typename Config>
inline bool normalize_saved_config_sensor_shadow(Config &config) {
  if (config.type == "text_sensor") { config.type = "sensor"; config.precision = "text"; config.entity.clear(); config.label.clear(); config.unit.clear(); config.icon_on = "Auto"; if (config.icon.empty()) config.icon = "Auto"; }
  if (config.type == "local_sensor") { config.type = "sensor"; config.sensor = "local"; config.icon_on = "Auto"; config.options.clear(); }
  if (config.type != "sensor") return false;
  if (config.icon.empty()) config.icon = "Auto";
  if (config.icon_on.empty()) config.icon_on = "Auto";
  if (config.sensor == "local") { config.icon_on = "Auto"; config.options.clear(); if (config.precision != "text" && config.precision != "1" && config.precision != "2") config.precision.clear(); if (config.precision != "text" && (config.icon.empty() || config.icon == "Auto")) config.icon = "Auto"; return true; }
  const std::string source = config.options; std::string out;
  if (config.precision != "icon" && config.precision != "text") append_large_numbers_option(out, source);
  if (config.precision == "text" && cfg_option_token_present(source, "state_labels")) {
    saved_config_shadow_append_option(out, "state_labels"); std::string input = cfg_option_value(source, "state_input"); std::string output = cfg_option_value(source, "state_output");
    if (input.empty() && !cfg_option_value(source, "state_high_label").empty()) { input = "high"; output = cfg_option_value(source, "state_high_label"); }
    else if (input.empty() && !cfg_option_value(source, "state_low_label").empty()) { input = "low"; output = cfg_option_value(source, "state_low_label"); }
    if (!input.empty()) saved_config_shadow_append_option(out, "state_input", input);
    if (!output.empty()) saved_config_shadow_append_option(out, "state_output", output);
    const std::string input_2 = cfg_option_value(source, "state_input_2"); const std::string output_2 = cfg_option_value(source, "state_output_2");
    if (!input_2.empty()) saved_config_shadow_append_option(out, "state_input_2", input_2);
    if (!output_2.empty()) saved_config_shadow_append_option(out, "state_output_2", output_2);
  }
  config.options = out; return true;
}

template<typename Config>
inline bool normalize_saved_config_action_shadow(Config &config) {
  if (config.type == "local") { config.type = "action"; config.sensor = "local"; }
  if (config.type == "option_select") { config.type = "action"; config.sensor = "input_select.select_option"; }
  if (config.type != "action") return false;
  if (saved_config_shadow_string_in(config.sensor, SAVED_CONFIG_SHADOW_ACTION_OPTION_SELECT_ACTIONS, sizeof(SAVED_CONFIG_SHADOW_ACTION_OPTION_SELECT_ACTIONS) / sizeof(SAVED_CONFIG_SHADOW_ACTION_OPTION_SELECT_ACTIONS[0]))) {
    config.sensor = "input_select.select_option"; config.unit.clear(); config.precision.clear(); config.options.clear(); config.icon_on = "Auto";
    if (config.icon.empty() || config.icon == "Auto" || config.icon == "Chevron Down") config.icon = "Flash";
    return true;
  }
  if (config.sensor == "local") {
    config.unit.clear(); config.precision.clear(); config.options.clear(); config.icon_on = "Auto";
    if (config.icon.empty() || config.icon == "Auto" || config.icon == "Flash") config.icon = "Gesture Tap";
    return true;
  }
  config.precision.clear(); const std::string source = config.options; std::string out; const std::string state_entity = cfg_option_value(source, "state_entity");
  if (!state_entity.empty()) { saved_config_shadow_append_option(out, "state_entity", state_entity); const std::string raw_precision = cfg_option_value(source, "state_precision");
    if (raw_precision == "icon" || raw_precision == "text") saved_config_shadow_append_option(out, "state_precision", raw_precision);
    else {
      const std::string state_unit = cfg_option_value(source, "state_unit");
      const bool numeric_precision = raw_precision == "0" || raw_precision == "1" || raw_precision == "2";
      if (!state_unit.empty()) saved_config_shadow_append_option(out, "state_unit", state_unit);
      if (numeric_precision) saved_config_shadow_append_option(out, "state_precision", raw_precision);
      append_large_numbers_option(out, source);
    }
  }
  if (config.sensor == "script.turn_on") {
    const std::string fields = cfg_option_value(source, "script_fields");
    if (!fields.empty()) saved_config_shadow_append_option(out, "script_fields", fields);
    if (cfg_option_token_present(source, "confirm_on")) {
      saved_config_shadow_append_option(out, "confirm_on");
      const std::string message = cfg_option_value(source, "confirm_message");
      const std::string yes = cfg_option_value(source, "confirm_yes");
      const std::string no = cfg_option_value(source, "confirm_no");
      if (!message.empty() && message != "Run this script?") saved_config_shadow_append_option(out, "confirm_message", message);
      if (!yes.empty() && yes != "Yes") saved_config_shadow_append_option(out, "confirm_yes", yes);
      if (!no.empty() && no != "No") saved_config_shadow_append_option(out, "confirm_no", no);
    }
  }
  config.options = out; return true;
}

template<typename Config>
inline bool normalize_saved_config_shadow(Config &config) {
  if (normalize_saved_config_vacuum_shadow(config)) return true;
  if (normalize_saved_config_sensor_shadow(config)) return true;
  return normalize_saved_config_action_shadow(config);
}
