#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG MEDIA HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

template<typename Config, typename FieldHook, typename OptionHook>
inline bool normalize_saved_config_media(Config &config, FieldHook normalize_fields,
                                         OptionHook normalize_options) {
  if (config.type != "media") return false;
  normalize_fields(config);
  config.options = normalize_options(config.options, config.sensor);
  return true;
}
