#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG LAWN MOWER HELPER - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

template<typename Config, typename FieldHook>
inline bool normalize_saved_config_mower(Config &config, FieldHook normalize_fields) {
  if (config.type == "lawn_mower") {
    normalize_fields(config);
    config.icon_on = "Auto";
    config.unit.clear();
    config.type = "lawn_mower";
    config.precision.clear();
    config.options.clear();
    return true;
  }
  return false;
}
