#pragma once

#include <cstdint>
#include <string>

// =============================================================================
// GENERATED CARD CONFIG CONTRACT - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

constexpr int CARD_CONTRACT_VERSION = 1;
namespace espcontrol::card_runtime {

enum class CardTypeId : uint8_t {
  SWITCH,
  ACTION,
  VACUUM,
  LAWN_MOWER,
  ALARM,
  ALARM_ACTION,
  CALENDAR,
  CLOCK,
  CLIMATE,
  CLIMATE_CONTROL,
  COVER,
  DOOR_WINDOW,
  PRESENCE,
  FAN_DIRECTION,
  FAN_OSCILLATE,
  FAN_PRESET,
  FAN_SPEED,
  FAN_CONTROL,
  FAN_SWITCH,
  GARAGE,
  GATE,
  INTERNAL,
  LIGHT_BRIGHTNESS,
  LIGHT_SWITCH,
  LIGHT_TEMPERATURE,
  LIGHT_CONTROL,
  LOCK,
  MEDIA,
  OPTION_SELECT,
  PUSH,
  SCREEN_LOCK,
  WEBHOOK,
  SENSOR,
  LOCAL_SENSOR,
  SLIDER,
  SUBPAGE,
  TIMEZONE,
  WEATHER,
  IMAGE,
  WEATHER_FORECAST,
  UNKNOWN,
};

enum class CardDriverId : uint8_t {
  TOGGLE,
  ACTION,
  VACUUM,
  LAWN_MOWER,
  ALARM,
  ALARM_ACTION,
  DATE_TIME,
  CLIMATE,
  COVER,
  COVER_MODAL,
  COVER_POSITION,
  COVER_TILT,
  COVER_TOGGLE,
  COVER_COMMAND,
  STATUS_ENTITY,
  FAN,
  FAN_CONTROL,
  ACCESS,
  INTERNAL,
  NUMERIC,
  LIGHT_TEMPERATURE,
  LIGHT_CONTROL,
  MEDIA,
  MEDIA_CONTROL,
  MEDIA_PLAY_PAUSE,
  MEDIA_TRANSPORT,
  MEDIA_VOLUME,
  MEDIA_POSITION,
  MEDIA_NOW_PLAYING,
  MEDIA_COVER_ART,
  MEDIA_PLAYLIST,
  OPTION_SELECT,
  PUSH,
  SCREEN_LOCK,
  WEBHOOK,
  SENSOR,
  SUBPAGE,
  WEATHER,
  IMAGE,
  UNKNOWN,
};

enum CardCapabilityFlag : uint16_t {
  CAPABILITY_NONE = 0,
  CAPABILITY_INFORMATION_ONLY = 1u << 0,
  CAPABILITY_SUBSCRIPTIONS = 1u << 1,
  CAPABILITY_ACTIONS = 1u << 2,
  CAPABILITY_NUMERIC_CONTROL = 1u << 3,
  CAPABILITY_MODAL = 1u << 4,
  CAPABILITY_RUNTIME_ALLOCATION = 1u << 5,
  CAPABILITY_SUBPAGE = 1u << 6,
};

struct CardRuntimeSpec {
  CardTypeId type = CardTypeId::UNKNOWN;
  CardDriverId driver = CardDriverId::UNKNOWN;
  uint16_t capabilities = CAPABILITY_NONE;
};

constexpr bool has_capability(const CardRuntimeSpec &spec, CardCapabilityFlag capability) {
  return (spec.capabilities & static_cast<uint16_t>(capability)) != 0;
}

inline CardTypeId card_type_id(const std::string &type) {
  if (type.empty()) return CardTypeId::SWITCH;
  if (type == "action") return CardTypeId::ACTION;
  if (type == "vacuum") return CardTypeId::VACUUM;
  if (type == "lawn_mower") return CardTypeId::LAWN_MOWER;
  if (type == "alarm") return CardTypeId::ALARM;
  if (type == "alarm_action") return CardTypeId::ALARM_ACTION;
  if (type == "calendar") return CardTypeId::CALENDAR;
  if (type == "clock") return CardTypeId::CLOCK;
  if (type == "climate") return CardTypeId::CLIMATE;
  if (type == "climate_control") return CardTypeId::CLIMATE_CONTROL;
  if (type == "cover") return CardTypeId::COVER;
  if (type == "door_window") return CardTypeId::DOOR_WINDOW;
  if (type == "presence") return CardTypeId::PRESENCE;
  if (type == "fan_direction") return CardTypeId::FAN_DIRECTION;
  if (type == "fan_oscillate") return CardTypeId::FAN_OSCILLATE;
  if (type == "fan_preset") return CardTypeId::FAN_PRESET;
  if (type == "fan_speed") return CardTypeId::FAN_SPEED;
  if (type == "fan_control") return CardTypeId::FAN_CONTROL;
  if (type == "fan_switch") return CardTypeId::FAN_SWITCH;
  if (type == "garage") return CardTypeId::GARAGE;
  if (type == "gate") return CardTypeId::GATE;
  if (type == "internal") return CardTypeId::INTERNAL;
  if (type == "light_brightness") return CardTypeId::LIGHT_BRIGHTNESS;
  if (type == "light_switch") return CardTypeId::LIGHT_SWITCH;
  if (type == "light_temperature") return CardTypeId::LIGHT_TEMPERATURE;
  if (type == "light_control") return CardTypeId::LIGHT_CONTROL;
  if (type == "lock") return CardTypeId::LOCK;
  if (type == "media") return CardTypeId::MEDIA;
  if (type == "option_select") return CardTypeId::OPTION_SELECT;
  if (type == "push") return CardTypeId::PUSH;
  if (type == "screen_lock") return CardTypeId::SCREEN_LOCK;
  if (type == "webhook") return CardTypeId::WEBHOOK;
  if (type == "sensor") return CardTypeId::SENSOR;
  if (type == "local_sensor") return CardTypeId::LOCAL_SENSOR;
  if (type == "slider") return CardTypeId::SLIDER;
  if (type == "subpage") return CardTypeId::SUBPAGE;
  if (type == "timezone") return CardTypeId::TIMEZONE;
  if (type == "weather") return CardTypeId::WEATHER;
  if (type == "image") return CardTypeId::IMAGE;
  if (type == "weather_forecast") return CardTypeId::WEATHER_FORECAST;
  return CardTypeId::UNKNOWN;
}

inline CardRuntimeSpec card_runtime_spec(CardTypeId type) {
  switch (type) {
    case CardTypeId::SWITCH: return {type, CardDriverId::TOGGLE, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_SUBPAGE)};
    case CardTypeId::ACTION: return {type, CardDriverId::ACTION, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::VACUUM: return {type, CardDriverId::VACUUM, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::LAWN_MOWER: return {type, CardDriverId::LAWN_MOWER, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::ALARM: return {type, CardDriverId::ALARM, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_MODAL | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::ALARM_ACTION: return {type, CardDriverId::ALARM_ACTION, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::CALENDAR: return {type, CardDriverId::DATE_TIME, static_cast<uint16_t>(CAPABILITY_INFORMATION_ONLY | CAPABILITY_SUBSCRIPTIONS | CAPABILITY_SUBPAGE)};
    case CardTypeId::CLOCK: return {type, CardDriverId::DATE_TIME, static_cast<uint16_t>(CAPABILITY_INFORMATION_ONLY | CAPABILITY_SUBSCRIPTIONS | CAPABILITY_SUBPAGE)};
    case CardTypeId::CLIMATE: return {type, CardDriverId::CLIMATE, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_NUMERIC_CONTROL | CAPABILITY_MODAL | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::CLIMATE_CONTROL: return {type, CardDriverId::CLIMATE, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_NUMERIC_CONTROL | CAPABILITY_MODAL | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::COVER: return {type, CardDriverId::COVER, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_NUMERIC_CONTROL | CAPABILITY_MODAL | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::DOOR_WINDOW: return {type, CardDriverId::STATUS_ENTITY, static_cast<uint16_t>(CAPABILITY_INFORMATION_ONLY | CAPABILITY_SUBSCRIPTIONS | CAPABILITY_SUBPAGE)};
    case CardTypeId::PRESENCE: return {type, CardDriverId::STATUS_ENTITY, static_cast<uint16_t>(CAPABILITY_INFORMATION_ONLY | CAPABILITY_SUBSCRIPTIONS | CAPABILITY_SUBPAGE)};
    case CardTypeId::FAN_DIRECTION: return {type, CardDriverId::FAN, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::FAN_OSCILLATE: return {type, CardDriverId::FAN, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::FAN_PRESET: return {type, CardDriverId::FAN, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::FAN_SPEED: return {type, CardDriverId::FAN, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_NUMERIC_CONTROL | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::FAN_CONTROL: return {type, CardDriverId::FAN_CONTROL, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_NUMERIC_CONTROL | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::FAN_SWITCH: return {type, CardDriverId::FAN, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::GARAGE: return {type, CardDriverId::ACCESS, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::GATE: return {type, CardDriverId::ACCESS, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::INTERNAL: return {type, CardDriverId::INTERNAL, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_SUBPAGE)};
    case CardTypeId::LIGHT_BRIGHTNESS: return {type, CardDriverId::NUMERIC, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_NUMERIC_CONTROL | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::LIGHT_SWITCH: return {type, CardDriverId::TOGGLE, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_SUBPAGE)};
    case CardTypeId::LIGHT_TEMPERATURE: return {type, CardDriverId::LIGHT_TEMPERATURE, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_NUMERIC_CONTROL | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::LIGHT_CONTROL: return {type, CardDriverId::LIGHT_CONTROL, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_NUMERIC_CONTROL | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::LOCK: return {type, CardDriverId::ACCESS, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::MEDIA: return {type, CardDriverId::MEDIA, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_NUMERIC_CONTROL | CAPABILITY_MODAL | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::OPTION_SELECT: return {type, CardDriverId::OPTION_SELECT, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::PUSH: return {type, CardDriverId::PUSH, static_cast<uint16_t>(CAPABILITY_ACTIONS | CAPABILITY_SUBPAGE)};
    case CardTypeId::SCREEN_LOCK: return {type, CardDriverId::SCREEN_LOCK, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_SUBPAGE)};
    case CardTypeId::WEBHOOK: return {type, CardDriverId::WEBHOOK, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_SUBPAGE)};
    case CardTypeId::SENSOR: return {type, CardDriverId::SENSOR, static_cast<uint16_t>(CAPABILITY_INFORMATION_ONLY | CAPABILITY_SUBSCRIPTIONS | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::LOCAL_SENSOR: return {type, CardDriverId::SENSOR, static_cast<uint16_t>(CAPABILITY_INFORMATION_ONLY | CAPABILITY_SUBSCRIPTIONS | CAPABILITY_SUBPAGE)};
    case CardTypeId::SLIDER: return {type, CardDriverId::NUMERIC, static_cast<uint16_t>(CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_NUMERIC_CONTROL | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::SUBPAGE: return {type, CardDriverId::SUBPAGE, static_cast<uint16_t>(CAPABILITY_ACTIONS | CAPABILITY_RUNTIME_ALLOCATION)};
    case CardTypeId::TIMEZONE: return {type, CardDriverId::DATE_TIME, static_cast<uint16_t>(CAPABILITY_INFORMATION_ONLY | CAPABILITY_SUBSCRIPTIONS | CAPABILITY_SUBPAGE)};
    case CardTypeId::WEATHER: return {type, CardDriverId::WEATHER, static_cast<uint16_t>(CAPABILITY_INFORMATION_ONLY | CAPABILITY_SUBSCRIPTIONS | CAPABILITY_SUBPAGE)};
    case CardTypeId::IMAGE: return {type, CardDriverId::IMAGE, static_cast<uint16_t>(CAPABILITY_INFORMATION_ONLY | CAPABILITY_SUBSCRIPTIONS | CAPABILITY_ACTIONS | CAPABILITY_MODAL | CAPABILITY_RUNTIME_ALLOCATION | CAPABILITY_SUBPAGE)};
    case CardTypeId::WEATHER_FORECAST: return {type, CardDriverId::WEATHER, static_cast<uint16_t>(CAPABILITY_INFORMATION_ONLY | CAPABILITY_SUBSCRIPTIONS | CAPABILITY_SUBPAGE)};
    default: return {};
  }
}

inline CardDriverId resolve_card_driver(CardTypeId type, const std::string &mode) {
  switch (type) {
    case CardTypeId::COVER:
      if (mode == "modal") return CardDriverId::COVER_MODAL;
      if (mode == "") return CardDriverId::COVER_POSITION;
      if (mode == "tilt") return CardDriverId::COVER_TILT;
      if (mode == "toggle") return CardDriverId::COVER_TOGGLE;
      if (mode == "open") return CardDriverId::COVER_COMMAND;
      if (mode == "close") return CardDriverId::COVER_COMMAND;
      if (mode == "stop") return CardDriverId::COVER_COMMAND;
      if (mode == "set_position") return CardDriverId::COVER_COMMAND;
      return CardDriverId::COVER_MODAL;
    case CardTypeId::MEDIA:
      if (mode == "control_modal") return CardDriverId::MEDIA_CONTROL;
      if (mode == "play_pause") return CardDriverId::MEDIA_PLAY_PAUSE;
      if (mode == "previous") return CardDriverId::MEDIA_TRANSPORT;
      if (mode == "next") return CardDriverId::MEDIA_TRANSPORT;
      if (mode == "volume") return CardDriverId::MEDIA_VOLUME;
      if (mode == "position") return CardDriverId::MEDIA_POSITION;
      if (mode == "now_playing") return CardDriverId::MEDIA_NOW_PLAYING;
      if (mode == "cover_art") return CardDriverId::MEDIA_COVER_ART;
      if (mode == "playlist") return CardDriverId::MEDIA_PLAYLIST;
      return CardDriverId::MEDIA_PLAY_PAUSE;
    default: return card_runtime_spec(type).driver;
  }
}

template<typename Config>
inline CardRuntimeSpec resolve_card_runtime(const Config &config) {
  CardRuntimeSpec spec = card_runtime_spec(card_type_id(config.type));
  switch (spec.type) {
    case CardTypeId::COVER:
      spec.driver = resolve_card_driver(spec.type, config.sensor);
      break;
    case CardTypeId::MEDIA:
      spec.driver = resolve_card_driver(spec.type, config.sensor);
      break;
    default:
      break;
  }
  return spec;
}

}  // namespace espcontrol::card_runtime

constexpr const char *CARD_CONTRACT_OPTION_SELECT_ACTION = "input_select.select_option";
inline const char *const CARD_CONTRACT_OPTION_SELECT_ACTIONS[] = {"input_select.select_option", "select.select_option"};
inline const char *const CARD_CONTRACT_BRIGHTNESS_SLIDER_TYPES[] = {"slider", "light_brightness", "fan_speed"};
inline const char *const CARD_CONTRACT_COVER_MODES[] = {"modal", "", "tilt", "toggle", "open", "close", "stop", "set_position"};
inline const char *const CARD_CONTRACT_COVER_CONTROL_TABS[] = {"position", "controls", "tilt", "presets"};
inline const char *const CARD_CONTRACT_GARAGE_MODES[] = {"", "open", "close"};
inline const char *const CARD_CONTRACT_GARAGE_LABEL_DISPLAY_MODES[] = {"label", "status"};
inline const char *const CARD_CONTRACT_GATE_MODES[] = {"", "open", "close", "stop"};
inline const char *const CARD_CONTRACT_GATE_LABEL_DISPLAY_MODES[] = {"label", "status"};
inline const char *const CARD_CONTRACT_INTERNAL_MODES[] = {"switch", "push"};
inline const char *const CARD_CONTRACT_LOCK_MODES[] = {"", "lock", "unlock"};
inline const char *const CARD_CONTRACT_MEDIA_MODES[] = {"control_modal", "play_pause", "previous", "next", "volume", "position", "now_playing", "cover_art", "playlist"};
inline const char *const CARD_CONTRACT_MEDIA_DISPLAY_MODES[] = {"", "state"};
inline const char *const CARD_CONTRACT_MEDIA_NOW_PLAYING_CONTROLS[] = {"", "progress", "play_pause"};
inline const char *const CARD_CONTRACT_MEDIA_LEGACY_MODES[] = {"controls"};
inline const char *const CARD_CONTRACT_MEDIA_STATE_DISPLAY_MODES[] = {"play_pause", "position"};
inline const char *const CARD_CONTRACT_ALARM_ACTION_MODES[] = {"away", "home", "night", "vacation", "disarm"};
inline const char *const CARD_CONTRACT_ALARM_DEFAULT_ACTIONS[] = {"away", "home", "disarm"};
inline const char *const CARD_CONTRACT_ALARM_ICON_DISPLAY_MODES[] = {"static", "status"};
inline const char *const CARD_CONTRACT_ALARM_LABEL_DISPLAY_MODES[] = {"name", "status"};
inline const char *const CARD_CONTRACT_IMAGE_MODAL_MODES[] = {"fill", "fit"};
inline const char *const CARD_CONTRACT_LIGHT_CONTROL_TABS[] = {"power", "brightness", "temperature", "color"};
inline const char *const CARD_CONTRACT_CLIMATE_LABEL_DISPLAY_MODES[] = {"label", "status", "actual", "target"};
inline const char *const CARD_CONTRACT_CLIMATE_NUMBER_DISPLAY_MODES[] = {"icon", "actual", "target"};
inline const char *const CARD_CONTRACT_CLIMATE_TEMPERATURE_STEPS[] = {"1", "0.5"};
inline const char *const CARD_CONTRACT_CLIMATE_PRECISION_VALUES[] = {"", "1", "2", "3"};
inline const char *const CARD_CONTRACT_WEATHER_FORECAST_PRECISIONS[] = {"today", "tomorrow"};
constexpr const char *CARD_CONTRACT_OPTION_NAME_ACTIONS = "actions";
constexpr const char *CARD_CONTRACT_OPTION_NAME_ACTIVE_COLOR = "active_color";
constexpr const char *CARD_CONTRACT_OPTION_NAME_ALARM_CARD_TYPE = "alarm_card_type";
constexpr const char *CARD_CONTRACT_OPTION_NAME_CLIMATE_TABS = "climate_tabs";
constexpr const char *CARD_CONTRACT_OPTION_NAME_CONFIRM_MESSAGE = "confirm_message";
constexpr const char *CARD_CONTRACT_OPTION_NAME_CONFIRM_NO = "confirm_no";
constexpr const char *CARD_CONTRACT_OPTION_NAME_CONFIRM_OFF = "confirm_off";
constexpr const char *CARD_CONTRACT_OPTION_NAME_CONFIRM_ON = "confirm_on";
constexpr const char *CARD_CONTRACT_OPTION_NAME_CONFIRM_YES = "confirm_yes";
constexpr const char *CARD_CONTRACT_OPTION_NAME_CONFIRMATION_MODE = "confirmation_mode";
constexpr const char *CARD_CONTRACT_OPTION_NAME_CONFIRMATION_REQUIRED = "confirmation_required";
constexpr const char *CARD_CONTRACT_OPTION_NAME_COVER_ART_ACTION = "cover_art_action";
constexpr const char *CARD_CONTRACT_OPTION_NAME_COVER_ART_DETAILS = "cover_art_details";
constexpr const char *CARD_CONTRACT_OPTION_NAME_COVER_MODE = "cover_mode";
constexpr const char *CARD_CONTRACT_OPTION_NAME_COVER_POSITION = "cover_position";
constexpr const char *CARD_CONTRACT_OPTION_NAME_COVER_TABS = "cover_tabs";
constexpr const char *CARD_CONTRACT_OPTION_NAME_DATE_TIME_MODE = "date_time_mode";
constexpr const char *CARD_CONTRACT_OPTION_NAME_FAN_TABS = "fan_tabs";
constexpr const char *CARD_CONTRACT_OPTION_NAME_GARAGE_MODE = "garage_mode";
constexpr const char *CARD_CONTRACT_OPTION_NAME_GATE_MODE = "gate_mode";
constexpr const char *CARD_CONTRACT_OPTION_NAME_ICON_DISPLAY = "icon_display";
constexpr const char *CARD_CONTRACT_OPTION_NAME_IMAGE_ICON = "image_icon";
constexpr const char *CARD_CONTRACT_OPTION_NAME_IMAGE_LABEL = "image_label";
constexpr const char *CARD_CONTRACT_OPTION_NAME_IMAGE_MODAL_MODE = "image_modal_mode";
constexpr const char *CARD_CONTRACT_OPTION_NAME_INTERNAL_MODE = "internal_mode";
constexpr const char *CARD_CONTRACT_OPTION_NAME_LABEL_DISPLAY = "label_display";
constexpr const char *CARD_CONTRACT_OPTION_NAME_LARGE_NUMBERS = "large_numbers";
constexpr const char *CARD_CONTRACT_OPTION_NAME_LAWN_MOWER_MODE = "lawn_mower_mode";
constexpr const char *CARD_CONTRACT_OPTION_NAME_LIGHT_TABS = "light_tabs";
constexpr const char *CARD_CONTRACT_OPTION_NAME_LOCK_MODE = "lock_mode";
constexpr const char *CARD_CONTRACT_OPTION_NAME_MEDIA_COVER_ART = "media_cover_art";
constexpr const char *CARD_CONTRACT_OPTION_NAME_MEDIA_DISPLAY = "media_display";
constexpr const char *CARD_CONTRACT_OPTION_NAME_MEDIA_MODE = "media_mode";
constexpr const char *CARD_CONTRACT_OPTION_NAME_MEDIA_NOW_PLAYING_CONTROLS = "media_now_playing_controls";
constexpr const char *CARD_CONTRACT_OPTION_NAME_NUMBER_DISPLAY = "number_display";
constexpr const char *CARD_CONTRACT_OPTION_NAME_ON_PATTERN = "on_pattern";
constexpr const char *CARD_CONTRACT_OPTION_NAME_PIN_ARM = "pin_arm";
constexpr const char *CARD_CONTRACT_OPTION_NAME_PIN_DISARM = "pin_disarm";
constexpr const char *CARD_CONTRACT_OPTION_NAME_PLAYLIST_CONTENT_ID = "playlist_content_id";
constexpr const char *CARD_CONTRACT_OPTION_NAME_PLAYLIST_CONTENT_TYPE = "playlist_content_type";
constexpr const char *CARD_CONTRACT_OPTION_NAME_PLAYLIST_PLAYER_SOURCE = "playlist_player_source";
constexpr const char *CARD_CONTRACT_OPTION_NAME_SCRIPT_FIELDS = "script_fields";
constexpr const char *CARD_CONTRACT_OPTION_NAME_STATE_ENTITY = "state_entity";
constexpr const char *CARD_CONTRACT_OPTION_NAME_STATE_HIGH_LABEL = "state_high_label";
constexpr const char *CARD_CONTRACT_OPTION_NAME_STATE_INPUT = "state_input";
constexpr const char *CARD_CONTRACT_OPTION_NAME_STATE_INPUT_2 = "state_input_2";
constexpr const char *CARD_CONTRACT_OPTION_NAME_STATE_LABELS = "state_labels";
constexpr const char *CARD_CONTRACT_OPTION_NAME_STATE_LOW_LABEL = "state_low_label";
constexpr const char *CARD_CONTRACT_OPTION_NAME_STATE_OUTPUT = "state_output";
constexpr const char *CARD_CONTRACT_OPTION_NAME_STATE_OUTPUT_2 = "state_output_2";
constexpr const char *CARD_CONTRACT_OPTION_NAME_STATE_PRECISION = "state_precision";
constexpr const char *CARD_CONTRACT_OPTION_NAME_STATE_UNIT = "state_unit";
constexpr const char *CARD_CONTRACT_OPTION_NAME_SUBPAGE_KIND = "subpage_kind";
constexpr const char *CARD_CONTRACT_OPTION_NAME_TEMPERATURE_STEP = "temperature_step";
constexpr const char *CARD_CONTRACT_OPTION_NAME_TIME_UNIT = "time_unit";
constexpr const char *CARD_CONTRACT_OPTION_NAME_VACUUM_MODE = "vacuum_mode";
constexpr const char *CARD_CONTRACT_OPTION_NAME_VOLUME_MAX = "volume_max";
constexpr const char *CARD_CONTRACT_OPTION_NAME_WEATHER_MODE = "weather_mode";
constexpr const char *CARD_CONTRACT_OPTION_NAME_WEBHOOK_HEADERS = "webhook_headers";
constexpr const char *CARD_CONTRACT_GARAGE_LABEL_DISPLAY_DEFAULT = "label";
constexpr const char *CARD_CONTRACT_GATE_LABEL_DISPLAY_DEFAULT = "label";
constexpr const char *CARD_CONTRACT_COVER_CONTROL_TABS_DEFAULT = "position|controls|tilt|presets";
constexpr const char *CARD_CONTRACT_MEDIA_DEFAULT_MODE = "play_pause";
constexpr int CARD_CONTRACT_MEDIA_VOLUME_MAX_MIN = 1;
constexpr int CARD_CONTRACT_MEDIA_VOLUME_MAX_MAX = 100;
constexpr int CARD_CONTRACT_MEDIA_VOLUME_MAX_DEFAULT = 100;
constexpr size_t CARD_CONTRACT_ALARM_MAX_VISIBLE_ACTIONS = 3;
constexpr const char *CARD_CONTRACT_ALARM_ICON_DISPLAY_DEFAULT = "status";
constexpr const char *CARD_CONTRACT_ALARM_LABEL_DISPLAY_DEFAULT = "status";
constexpr const char *CARD_CONTRACT_IMAGE_MODAL_MODE_DEFAULT = "fill";
constexpr const char *CARD_CONTRACT_LIGHT_CONTROL_TABS_DEFAULT = "power|brightness|temperature|color";
constexpr const char *CARD_CONTRACT_CLIMATE_LABEL_DISPLAY_DEFAULT = "label";
constexpr const char *CARD_CONTRACT_CLIMATE_NUMBER_DISPLAY_DEFAULT = "target";
constexpr const char *CARD_CONTRACT_CLIMATE_TEMPERATURE_STEP_DEFAULT = "1";

inline bool card_contract_string_in(const std::string &value, const char *const *items, size_t count) {
  for (size_t i = 0; i < count; i++) {
    if (value == items[i]) return true;
  }
  return false;
}

inline bool card_contract_is_brightness_slider_type(const std::string &type) {
  return card_contract_string_in(type, CARD_CONTRACT_BRIGHTNESS_SLIDER_TYPES,
    sizeof(CARD_CONTRACT_BRIGHTNESS_SLIDER_TYPES) / sizeof(CARD_CONTRACT_BRIGHTNESS_SLIDER_TYPES[0]));
}

inline bool card_contract_is_option_select_action(const std::string &action) {
  return card_contract_string_in(action, CARD_CONTRACT_OPTION_SELECT_ACTIONS,
    sizeof(CARD_CONTRACT_OPTION_SELECT_ACTIONS) / sizeof(CARD_CONTRACT_OPTION_SELECT_ACTIONS[0]));
}

inline bool card_contract_cover_mode_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_COVER_MODES,
    sizeof(CARD_CONTRACT_COVER_MODES) / sizeof(CARD_CONTRACT_COVER_MODES[0]));
}

inline bool card_contract_cover_control_tab_valid(const std::string &tab) {
  return card_contract_string_in(tab, CARD_CONTRACT_COVER_CONTROL_TABS,
    sizeof(CARD_CONTRACT_COVER_CONTROL_TABS) / sizeof(CARD_CONTRACT_COVER_CONTROL_TABS[0]));
}

inline bool card_contract_garage_mode_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_GARAGE_MODES,
    sizeof(CARD_CONTRACT_GARAGE_MODES) / sizeof(CARD_CONTRACT_GARAGE_MODES[0]));
}

inline bool card_contract_garage_label_display_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_GARAGE_LABEL_DISPLAY_MODES,
    sizeof(CARD_CONTRACT_GARAGE_LABEL_DISPLAY_MODES) / sizeof(CARD_CONTRACT_GARAGE_LABEL_DISPLAY_MODES[0]));
}

inline bool card_contract_gate_mode_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_GATE_MODES,
    sizeof(CARD_CONTRACT_GATE_MODES) / sizeof(CARD_CONTRACT_GATE_MODES[0]));
}

inline bool card_contract_gate_label_display_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_GATE_LABEL_DISPLAY_MODES,
    sizeof(CARD_CONTRACT_GATE_LABEL_DISPLAY_MODES) / sizeof(CARD_CONTRACT_GATE_LABEL_DISPLAY_MODES[0]));
}

inline bool card_contract_internal_mode_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_INTERNAL_MODES,
    sizeof(CARD_CONTRACT_INTERNAL_MODES) / sizeof(CARD_CONTRACT_INTERNAL_MODES[0]));
}

inline bool card_contract_lock_mode_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_LOCK_MODES,
    sizeof(CARD_CONTRACT_LOCK_MODES) / sizeof(CARD_CONTRACT_LOCK_MODES[0]));
}

inline bool card_contract_media_mode_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_MEDIA_MODES,
    sizeof(CARD_CONTRACT_MEDIA_MODES) / sizeof(CARD_CONTRACT_MEDIA_MODES[0]));
}

inline bool card_contract_media_legacy_mode(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_MEDIA_LEGACY_MODES,
    sizeof(CARD_CONTRACT_MEDIA_LEGACY_MODES) / sizeof(CARD_CONTRACT_MEDIA_LEGACY_MODES[0]));
}

inline bool card_contract_media_state_display_mode(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_MEDIA_STATE_DISPLAY_MODES,
    sizeof(CARD_CONTRACT_MEDIA_STATE_DISPLAY_MODES) / sizeof(CARD_CONTRACT_MEDIA_STATE_DISPLAY_MODES[0]));
}

inline bool card_contract_alarm_action_mode_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_ALARM_ACTION_MODES,
    sizeof(CARD_CONTRACT_ALARM_ACTION_MODES) / sizeof(CARD_CONTRACT_ALARM_ACTION_MODES[0]));
}

inline size_t card_contract_alarm_default_action_count() {
  return sizeof(CARD_CONTRACT_ALARM_DEFAULT_ACTIONS) / sizeof(CARD_CONTRACT_ALARM_DEFAULT_ACTIONS[0]);
}

inline const char *card_contract_alarm_default_action_at(size_t index) {
  return index < card_contract_alarm_default_action_count()
    ? CARD_CONTRACT_ALARM_DEFAULT_ACTIONS[index]
    : "";
}

inline bool card_contract_alarm_icon_display_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_ALARM_ICON_DISPLAY_MODES,
    sizeof(CARD_CONTRACT_ALARM_ICON_DISPLAY_MODES) / sizeof(CARD_CONTRACT_ALARM_ICON_DISPLAY_MODES[0]));
}

inline bool card_contract_alarm_label_display_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_ALARM_LABEL_DISPLAY_MODES,
    sizeof(CARD_CONTRACT_ALARM_LABEL_DISPLAY_MODES) / sizeof(CARD_CONTRACT_ALARM_LABEL_DISPLAY_MODES[0]));
}

inline bool card_contract_image_modal_mode_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_IMAGE_MODAL_MODES,
    sizeof(CARD_CONTRACT_IMAGE_MODAL_MODES) / sizeof(CARD_CONTRACT_IMAGE_MODAL_MODES[0]));
}

inline bool card_contract_light_control_tab_valid(const std::string &tab) {
  return card_contract_string_in(tab, CARD_CONTRACT_LIGHT_CONTROL_TABS,
    sizeof(CARD_CONTRACT_LIGHT_CONTROL_TABS) / sizeof(CARD_CONTRACT_LIGHT_CONTROL_TABS[0]));
}

inline bool card_contract_climate_label_display_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_CLIMATE_LABEL_DISPLAY_MODES,
    sizeof(CARD_CONTRACT_CLIMATE_LABEL_DISPLAY_MODES) / sizeof(CARD_CONTRACT_CLIMATE_LABEL_DISPLAY_MODES[0]));
}

inline bool card_contract_climate_number_display_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_CLIMATE_NUMBER_DISPLAY_MODES,
    sizeof(CARD_CONTRACT_CLIMATE_NUMBER_DISPLAY_MODES) / sizeof(CARD_CONTRACT_CLIMATE_NUMBER_DISPLAY_MODES[0]));
}

inline bool card_contract_climate_temperature_step_valid(const std::string &step) {
  return card_contract_string_in(step, CARD_CONTRACT_CLIMATE_TEMPERATURE_STEPS,
    sizeof(CARD_CONTRACT_CLIMATE_TEMPERATURE_STEPS) / sizeof(CARD_CONTRACT_CLIMATE_TEMPERATURE_STEPS[0]));
}

inline bool card_contract_climate_precision_valid(const std::string &precision) {
  return card_contract_string_in(precision, CARD_CONTRACT_CLIMATE_PRECISION_VALUES,
    sizeof(CARD_CONTRACT_CLIMATE_PRECISION_VALUES) / sizeof(CARD_CONTRACT_CLIMATE_PRECISION_VALUES[0]));
}

inline bool card_contract_weather_forecast_precision(const std::string &precision) {
  return card_contract_string_in(precision, CARD_CONTRACT_WEATHER_FORECAST_PRECISIONS,
    sizeof(CARD_CONTRACT_WEATHER_FORECAST_PRECISIONS) / sizeof(CARD_CONTRACT_WEATHER_FORECAST_PRECISIONS[0]));
}

inline const char *card_contract_cover_command_service(const std::string &mode) {
  if (mode == "open") return "cover.open_cover";
  if (mode == "close") return "cover.close_cover";
  if (mode == "stop") return "cover.stop_cover";
  if (mode == "set_position") return "cover.set_cover_position";
  return nullptr;
}

inline const char *card_contract_lock_command_service(const std::string &mode) {
  if (mode == "lock") return "lock.lock";
  if (mode == "unlock") return "lock.unlock";
  return nullptr;
}

inline const char *card_contract_lock_toggle_service(const std::string &state) {
  if (state == "locked") return "lock.unlock";
  return "lock.lock";
}

inline const char *card_contract_media_playback_service(const std::string &mode) {
  if (mode == "play_pause") return "media_player.media_play_pause";
  if (mode == "previous") return "media_player.media_previous_track";
  if (mode == "next") return "media_player.media_next_track";
  return "media_player.media_play_pause";
}

inline const char *card_contract_alarm_action_service(const std::string &mode) {
  if (mode == "away") return "alarm_control_panel.alarm_arm_away";
  if (mode == "home") return "alarm_control_panel.alarm_arm_home";
  if (mode == "night") return "alarm_control_panel.alarm_arm_night";
  if (mode == "vacation") return "alarm_control_panel.alarm_arm_vacation";
  if (mode == "disarm") return "alarm_control_panel.alarm_disarm";
  return nullptr;
}

inline const char *card_contract_alarm_action_icon_name(const std::string &mode) {
  if (mode == "away") return "Shield Lock";
  if (mode == "home") return "Shield Home";
  if (mode == "night") return "Weather Night";
  if (mode == "vacation") return "Airplane";
  if (mode == "disarm") return "Shield Off";
  return "Alarm";
}

inline bool card_contract_alarm_action_legacy_icon_name(const std::string &mode, const std::string &icon) {
  if (mode == "away") return icon == "Security";
  if (mode == "home") return icon == "Home";
  if (mode == "night") return icon == "Weather Night";
  if (mode == "vacation") return icon == "Airplane";
  if (mode == "disarm") return icon == "Lock Open";
  return false;
}

inline const char *card_contract_card_label(const std::string &type) {
  if (type == "") return "Switch";
  if (type == "action") return "Action";
  if (type == "vacuum") return "Vacuum";
  if (type == "lawn_mower") return "Lawn Mower";
  if (type == "alarm") return "Alarm";
  if (type == "alarm_action") return "Alarm";
  if (type == "calendar") return "Date & Time";
  if (type == "clock") return "Date & Time";
  if (type == "climate") return "Climate";
  if (type == "climate_control") return "All Controls";
  if (type == "cover") return "Cover";
  if (type == "door_window") return "Doors & Windows";
  if (type == "presence") return "Presence";
  if (type == "fan_direction") return "Fans";
  if (type == "fan_oscillate") return "Fans";
  if (type == "fan_preset") return "Fans";
  if (type == "fan_speed") return "Fans";
  if (type == "fan_control") return "Fans";
  if (type == "fan_switch") return "Fans";
  if (type == "garage") return "Garage Door";
  if (type == "gate") return "Gate";
  if (type == "internal") return "Internal Switches";
  if (type == "light_brightness") return "Lights";
  if (type == "light_switch") return "Lights";
  if (type == "light_temperature") return "Lights";
  if (type == "light_control") return "Lights";
  if (type == "lock") return "Lock";
  if (type == "media") return "Media";
  if (type == "option_select") return "Option Select";
  if (type == "push") return "Trigger";
  if (type == "screen_lock") return "Screen Lock";
  if (type == "webhook") return "Webhook";
  if (type == "sensor") return "Sensor";
  if (type == "local_sensor") return "Local Sensor";
  if (type == "slider") return "Slider";
  if (type == "subpage") return "Subpage";
  if (type == "timezone") return "Date & Time";
  if (type == "weather") return "Weather";
  if (type == "image") return "Camera Card";
  if (type == "weather_forecast") return "Weather Forecast";
  return type.empty() ? "Switch" : type.c_str();
}

inline bool card_contract_allow_in_subpage(const std::string &type) {
  if (type == "") return true;
  if (type == "action") return true;
  if (type == "vacuum") return true;
  if (type == "lawn_mower") return true;
  if (type == "alarm") return true;
  if (type == "alarm_action") return true;
  if (type == "calendar") return true;
  if (type == "clock") return true;
  if (type == "climate") return true;
  if (type == "climate_control") return true;
  if (type == "cover") return true;
  if (type == "door_window") return true;
  if (type == "presence") return true;
  if (type == "fan_direction") return true;
  if (type == "fan_oscillate") return true;
  if (type == "fan_preset") return true;
  if (type == "fan_speed") return true;
  if (type == "fan_control") return true;
  if (type == "fan_switch") return true;
  if (type == "garage") return true;
  if (type == "gate") return true;
  if (type == "internal") return true;
  if (type == "light_brightness") return true;
  if (type == "light_switch") return true;
  if (type == "light_temperature") return true;
  if (type == "light_control") return true;
  if (type == "lock") return true;
  if (type == "media") return true;
  if (type == "option_select") return true;
  if (type == "push") return true;
  if (type == "screen_lock") return true;
  if (type == "webhook") return true;
  if (type == "sensor") return true;
  if (type == "local_sensor") return true;
  if (type == "slider") return true;
  if (type == "subpage") return false;
  if (type == "timezone") return true;
  if (type == "weather") return true;
  if (type == "image") return true;
  if (type == "weather_forecast") return true;
  return false;
}

inline const char *card_contract_default_icon_name(const std::string &type) {
  if (type == "") return "Auto";
  if (type == "action") return "Flash";
  if (type == "vacuum") return "Robot Vacuum";
  if (type == "lawn_mower") return "Robot Mower";
  if (type == "alarm") return "Security";
  if (type == "alarm_action") return "Shield Lock";
  if (type == "calendar") return "Auto";
  if (type == "clock") return "Auto";
  if (type == "climate") return "Thermostat";
  if (type == "climate_control") return "Thermostat";
  if (type == "cover") return "Blinds";
  if (type == "door_window") return "Door";
  if (type == "presence") return "Motion Sensor Off";
  if (type == "fan_direction") return "Swap Horizontal";
  if (type == "fan_oscillate") return "Fan";
  if (type == "fan_preset") return "Fan Auto";
  if (type == "fan_speed") return "Fan Speed 2";
  if (type == "fan_control") return "Fan";
  if (type == "fan_switch") return "Fan Off";
  if (type == "garage") return "Garage";
  if (type == "gate") return "Gate";
  if (type == "internal") return "Lightbulb Outline";
  if (type == "light_brightness") return "Lightbulb Outline";
  if (type == "light_switch") return "Lightbulb Outline";
  if (type == "light_temperature") return "Lightbulb";
  if (type == "light_control") return "Lightbulb Outline";
  if (type == "lock") return "Lock";
  if (type == "media") return "Auto";
  if (type == "option_select") return "Flash";
  if (type == "push") return "Gesture Tap";
  if (type == "screen_lock") return "Lock";
  if (type == "webhook") return "Auto";
  if (type == "sensor") return "Auto";
  if (type == "local_sensor") return "Auto";
  if (type == "slider") return "Auto";
  if (type == "subpage") return "Auto";
  if (type == "timezone") return "Auto";
  if (type == "weather") return "Auto";
  if (type == "image") return "Auto";
  if (type == "weather_forecast") return "Auto";
  return "Auto";
}

inline const char *card_contract_default_icon_on_name(const std::string &type) {
  if (type == "") return "Auto";
  if (type == "action") return "Auto";
  if (type == "vacuum") return "Auto";
  if (type == "lawn_mower") return "Auto";
  if (type == "alarm") return "Auto";
  if (type == "alarm_action") return "Auto";
  if (type == "calendar") return "Auto";
  if (type == "clock") return "Auto";
  if (type == "climate") return "Auto";
  if (type == "climate_control") return "Auto";
  if (type == "cover") return "Blinds Open";
  if (type == "door_window") return "Door Open";
  if (type == "presence") return "Motion Sensor";
  if (type == "fan_direction") return "Auto";
  if (type == "fan_oscillate") return "Auto";
  if (type == "fan_preset") return "Auto";
  if (type == "fan_speed") return "Auto";
  if (type == "fan_control") return "Auto";
  if (type == "fan_switch") return "Fan";
  if (type == "garage") return "Garage Open";
  if (type == "gate") return "Gate Open";
  if (type == "internal") return "Lightbulb";
  if (type == "light_brightness") return "Lightbulb";
  if (type == "light_switch") return "Lightbulb";
  if (type == "light_temperature") return "Auto";
  if (type == "light_control") return "Lightbulb";
  if (type == "lock") return "Lock Open";
  if (type == "media") return "Auto";
  if (type == "option_select") return "Auto";
  if (type == "push") return "Auto";
  if (type == "screen_lock") return "Lock Open";
  if (type == "webhook") return "Auto";
  if (type == "sensor") return "Auto";
  if (type == "local_sensor") return "Auto";
  if (type == "slider") return "Auto";
  if (type == "subpage") return "Auto";
  if (type == "timezone") return "Auto";
  if (type == "weather") return "Auto";
  if (type == "image") return "Auto";
  if (type == "weather_forecast") return "Auto";
  return "Auto";
}

inline bool card_contract_is_fan_card_type(const std::string &type) {
  return type == "fan_switch" ||
         type == "fan_speed" ||
         type == "fan_control" ||
         type == "fan_oscillate" ||
         type == "fan_direction" ||
         type == "fan_preset";
}

inline const char *card_contract_fan_default_icon_name(const std::string &type) {
  if (type == "fan_switch") return "Fan Off";
  if (type == "fan_speed") return "Fan Speed 2";
  if (type == "fan_control") return "Fan";
  if (type == "fan_oscillate") return "Fan";
  if (type == "fan_direction") return "Swap Horizontal";
  if (type == "fan_preset") return "Fan Auto";
  return "Fan Speed 2";
}

inline const char *card_contract_fan_default_icon_on_name(const std::string &type) {
  if (type == "fan_switch") return "Fan";
  return "Auto";
}

inline bool card_contract_large_numbers_supported(const std::string &type, const std::string &precision) {
  if (type == "sensor") return precision != "icon" && precision != "text";
  if (type == "weather") return precision == "today" || precision == "tomorrow";
  return type == "" || type == "action" || type == "calendar" || type == "clock" ||
         type == "climate" || type == "media" || type == "subpage" ||
         type == "timezone";
}

inline const char *card_contract_subpage_type_code(const std::string &type) {
  if (type == "action") return "A";
  if (type == "calendar") return "D";
  if (type == "clock") return "CK";
  if (type == "timezone") return "T";
  if (type == "sensor") return "S";
  if (type == "local_sensor") return "LS";
  if (type == "door_window") return "X";
  if (type == "presence") return "PR";
  if (type == "weather") return "W";
  if (type == "weather_forecast") return "F";
  if (type == "option_select") return "U";
  if (type == "fan_switch") return "B";
  if (type == "fan_speed") return "J";
  if (type == "fan_control") return "FC";
  if (type == "fan_oscillate") return "O";
  if (type == "fan_direction") return "E";
  if (type == "fan_preset") return "Z";
  if (type == "light_brightness") return "V";
  if (type == "light_switch") return "Q";
  if (type == "light_control") return "LC";
  if (type == "alarm") return "Y";
  if (type == "alarm_action") return "AA";
  if (type == "slider") return "L";
  if (type == "cover") return "C";
  if (type == "vacuum") return "VC";
  if (type == "lawn_mower") return "LM";
  if (type == "light_temperature") return "N";
  if (type == "garage") return "R";
  if (type == "gate") return "GT";
  if (type == "lock") return "K";
  if (type == "media") return "M";
  if (type == "climate") return "H";
  if (type == "climate_control") return "HC";
  if (type == "push") return "P";
  if (type == "screen_lock") return "SL";
  if (type == "webhook") return "WH";
  if (type == "internal") return "I";
  if (type == "subpage") return "G";
  return type.c_str();
}

inline std::string card_contract_subpage_type_from_code(const std::string &code) {
  if (code == "A") return "action";
  if (code == "D") return "calendar";
  if (code == "CK") return "clock";
  if (code == "T") return "timezone";
  if (code == "S") return "sensor";
  if (code == "LS") return "local_sensor";
  if (code == "X") return "door_window";
  if (code == "PR") return "presence";
  if (code == "W") return "weather";
  if (code == "F") return "weather_forecast";
  if (code == "U") return "option_select";
  if (code == "B") return "fan_switch";
  if (code == "J") return "fan_speed";
  if (code == "FC") return "fan_control";
  if (code == "O") return "fan_oscillate";
  if (code == "E") return "fan_direction";
  if (code == "Z") return "fan_preset";
  if (code == "V") return "light_brightness";
  if (code == "Q") return "light_switch";
  if (code == "LC") return "light_control";
  if (code == "Y") return "alarm";
  if (code == "AA") return "alarm_action";
  if (code == "L") return "slider";
  if (code == "C") return "cover";
  if (code == "VC") return "vacuum";
  if (code == "LM") return "lawn_mower";
  if (code == "N") return "light_temperature";
  if (code == "R") return "garage";
  if (code == "GT") return "gate";
  if (code == "K") return "lock";
  if (code == "M") return "media";
  if (code == "H") return "climate";
  if (code == "HC") return "climate_control";
  if (code == "P") return "push";
  if (code == "SL") return "screen_lock";
  if (code == "WH") return "webhook";
  if (code == "I") return "internal";
  if (code == "G") return "subpage";
  return code;
}
