#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG STATIC CARD HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

template<typename Config>
inline bool normalize_saved_config_static(Config &config) {
  if (config.type == "internal") {
    config.type = "internal";
    config.options.clear();
    return true;
  }
  if (config.type == "light_brightness") {
    config.sensor.clear();
    config.type = "light_brightness";
    config.options.clear();
    return true;
  }
  if (config.type == "light_switch") {
    config.sensor.clear();
    config.unit.clear();
    config.type = "light_switch";
    config.precision.clear();
    config.options.clear();
    return true;
  }
  if (config.type == "light_temperature") {
    config.type = "light_temperature";
    config.options.clear();
    return true;
  }
  if (config.type == "push") {
    config.type = "push";
    config.options.clear();
    return true;
  }
  if (config.type == "screen_lock") {
    config.entity.clear();
    config.label.clear();
    config.icon = "Lock";
    config.icon_on = "Lock Open";
    config.sensor.clear();
    config.unit.clear();
    config.type = "screen_lock";
    config.precision.clear();
    config.options.clear();
    return true;
  }
  if (config.type == "slider") {
    config.sensor.clear();
    config.type = "slider";
    config.options.clear();
    return true;
  }
  return false;
}
