#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG SECURITY HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

template<typename Config, typename FieldHook, typename OptionHook>
inline bool normalize_saved_config_security(Config &config, FieldHook normalize_fields,
                                            OptionHook normalize_options) {
  if (config.type == "alarm") {
    normalize_fields(config);
    config.icon_on = "Auto";
    config.sensor.clear();
    config.unit.clear();
    config.type = "alarm";
    config.precision.clear();
    config.options = normalize_options(config.options, config);
    return true;
  }
  if (config.type == "alarm_action") {
    normalize_fields(config);
    config.icon_on = "Auto";
    config.unit.clear();
    config.type = "alarm_action";
    config.precision.clear();
    config.options = normalize_options(config.options, config);
    return true;
  }
  return false;
}
