#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG ACTION HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

template<typename Config>
inline bool migrate_saved_config_action_legacy(Config &config) {
  if (config.type == "local") {
    config.type = "action";
    config.sensor = "local";
    config.unit.clear();
    config.precision.clear();
    config.options.clear();
    config.icon_on = "Auto";
    return true;
  }
  if (config.type == "option_select") {
    config.type = "action";
    config.sensor = "input_select.select_option";
    config.unit.clear();
    config.precision.clear();
    config.options.clear();
    config.icon_on = "Auto";
    return true;
  }
  return false;
}

template<typename Config, typename FieldHook, typename OptionHook>
inline bool normalize_saved_config_action(Config &config, FieldHook normalize_fields,
                                          OptionHook normalize_options) {
  if (config.type != "action") return false;
  normalize_fields(config);
  config.options = normalize_options(config.options, config.sensor);
  return true;
}
