#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG WEATHER HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

template<typename Config>
inline bool migrate_saved_config_weather_legacy(Config &config) {
  if (config.type != "weather_forecast") return false;
  config.type = "weather";
  config.precision = "tomorrow";
  return true;
}

template<typename Config, typename FieldHook, typename OptionHook>
inline bool normalize_saved_config_weather(Config &config, bool was_legacy_forecast,
                                           FieldHook normalize_fields,
                                           OptionHook normalize_options) {
  if (config.type != "weather") return false;
  normalize_fields(config, was_legacy_forecast);
    config.sensor.clear();
    config.type = "weather";
  config.options = normalize_options(config.options, config);
  return true;
}
