#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG IMAGE HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

template<typename Config, typename FieldHook, typename OptionHook>
inline bool normalize_saved_config_image(Config &config, FieldHook normalize_fields,
                                         OptionHook normalize_options) {
  if (config.type != "image") return false;
  normalize_fields(config);
    config.icon_on = "Auto";
    config.sensor.clear();
    config.unit.clear();
    config.type = "image";
    config.precision.clear();
  config.options = normalize_options(config.options, config);
  return true;
}
