#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG FAN HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

template<typename Config, typename FieldHook, typename OptionHook>
inline bool normalize_saved_config_fan(Config &config, FieldHook normalize_fields,
                                      OptionHook normalize_options) {
  if (config.type == "fan_direction") {
    normalize_fields(config);
    config.sensor.clear();
    config.unit.clear();
    config.type = "fan_direction";
    config.precision.clear();
    config.options.clear();
    return true;
  }
  if (config.type == "fan_oscillate") {
    normalize_fields(config);
    config.sensor.clear();
    config.unit.clear();
    config.type = "fan_oscillate";
    config.precision.clear();
    config.options.clear();
    return true;
  }
  if (config.type == "fan_preset") {
    normalize_fields(config);
    config.sensor.clear();
    config.unit.clear();
    config.type = "fan_preset";
    config.precision.clear();
    config.options.clear();
    return true;
  }
  if (config.type == "fan_speed") {
    normalize_fields(config);
    config.sensor.clear();
    config.unit.clear();
    config.type = "fan_speed";
    config.precision.clear();
    config.options.clear();
    return true;
  }
  if (config.type == "fan_control") {
    normalize_fields(config);
    config.sensor.clear();
    config.unit.clear();
    config.type = "fan_control";
    config.precision.clear();
    config.options = normalize_options(config.options);
    return true;
  }
  if (config.type == "fan_switch") {
    normalize_fields(config);
    config.sensor.clear();
    config.unit.clear();
    config.type = "fan_switch";
    config.precision.clear();
    config.options.clear();
    return true;
  }
  return false;
}
