# =============================================================================
# DEV CONFIG - Local development entry point (4.3" P4 portrait panel)
# =============================================================================
# Flash with: esphome run dev.yaml
# =============================================================================

substitutions:
  cover_art_placeholder_file: "../../common/assets/cover_art_placeholder.svg"
  name: "espcontrol-43inch-p4"
  friendly_name: "EspControl 4.3inch P4"
  espcontrol_component_url: "../.."
  mdi_font_file: "../../common/assets/fonts/materialdesignicons-webfont-7.4.47.ttf"
  espcontrol_component_ref: "HEAD"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  js_url: ""
  js_include: "../../docs/public/webserver/guition-esp32-p4-jc4880p443/www.js"

packages:
  espcontrol: !include packages.yaml
